### ISSUE TITLE
Status of research

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#1]
Hi,

I'm interested in your efforts to develop a NodeJS H5P integration. Have you done any research on how the editor works so far?

Best
Sebastian

**Comment by JPSchellenberg** [comment]
Hey,

yes, I have done some research and managed to get the Editor running with a few bugs. Tomorrow, I will push my work and you can have a look at it. I will also publish some kind of documentation about how the H5P-editor works.

Best
JP

**Comment by JPSchellenberg** [comment]
Hey,

the current state is that we need to implement the "Ajax-Endpoint", which is described [here](https://github.com/Lumieducation/H5P-Editor-Nodejs-library/issues/4) and the progress is documented in [this milestone](https://github.com/Lumieducation/H5P-Editor-Nodejs-library/milestone/1).

I hope this helps you to understand the Editor a little bit better.
