### ISSUE TITLE
Project requires persistence layer

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#10]
The editor saves state in various places, e.g. when refreshing the Content Type Cache:

* it stores a unique ID assigned to the instance by the H5P Hub, which has to be used in subsequent requests
* it stores information about when the it last downloaded the information from the Hub
* the data of the content cache itself must also be stored somewhere
* There are other uses of persistence such as configuration settings (e.g. if usage statistics should be sent).

In the original H5P implementation this is done by calling interface functions which are implemented by the H5P integrations (into WordPress, Moodle). The Moodle implementation for example stores the data in the SQL database. 

Do you want to take the same approach here? If there is an interface to call, people using the library could then employ whatever they want (MongoDB, files, ...).

**Comment by JPSchellenberg** [comment]
Yes, I think we should use the same approach. We should be agnostic of the database/storage and provide interfaces, that the user has to implement. In my first draft, I had such an interface, but it was coupled with express.

We would need a list of all functions that have to be implemented.

It could look something like this:
```ts
  export interface IH5PInterface {
    load_content_json: (
        req: express.Request,
        cb: (error: Error, content: IContent) => void
    ) => void;
    load_content: (
        req: express.Request,
        file_name: string,
        cb: (error: Error, buffer: Buffer) => void
    ) => void;
    load_h5p_json: (
        req: express.Request,
        cb: (error: Error, h5p_json: IH5P) => void
    ) => void;
    load_library: (
        name: string,
        cb: (error: Error, library: ILibrary) => void
    ) => void;

    save_content_json: (
        req: express.Request,
        content_json: JSON,
        done: (error: Error) => void
    ) => void;
    save_content: (
        req: express.Request,
        file_name: string,
        content: Buffer
    ) => Promise<boolean>;
    save_h5p_json: (
        req: express.Request,
        h5p_json: JSON,
        done: (error: Error) => void
    ) => void;
}
```

**Comment by JPSchellenberg** [comment]
Hey, 
in the newest PR (#14 ), we added a storage interface that could look something like this:
```ts
export interface IStorage {
    loadLibrary: (
        machineName: string,
        majorVersion: number,
        minorVersion: number
    ) => Promise<ILIbrary>;

    loadSemantics: (
        machineName: string,
        majroVersion: number,
        minorVersion: number
    ) => Promise<ISemantics>;

    loadTranslations: (
        machineName: string,
        majorVersion: number,
        minorVersion: number,
        language: string
    ) => Promise<ITranslation>;

    // used to load and save data that is stored in the content.json in the /content folder of a .h5p file
    loadContent: (contentId: string) => Promise<IContent>;
    saveContent: (contentId: string, content: IContent) => Promise<IContent>;

    // used to load and save data that is stored in the h5p.json of a .h5p file
    loadH5P: (contentId: string) => Promise<IH5P>;
    saveH5P: (contentId: string, h5p: IH5P) => Promise<IH5P>;

    // used to load and save arbitrary data
    save: <T>(key: string, value: any) => Promise<T>;
    load: <T>(key: string) => Promise<T>;
}
```

The storage interface is a class that implements functions in order to save and load data and is passed as the first argument into the H5PEditor-constructor.

Best 
JP
