### ISSUE TITLE
Implement the "save content state" option of H5P core

### ISSUE THREAD

**Issue by otacke** [Lumieducation/H5P-Nodejs-library#1014]
**Is your feature request related to a problem? Please describe.**
When using the node.js port of H5P core, you cannot save the current content's state and resume later.

**Describe the solution you'd like**
- I'd like the node.js port of H5P core to call instances' getCurrentState function (if present) in regular intervals and on instances' xAPI completed/progressed statements in order to save the instances' current state, cmp. https://github.com/h5p/h5p-php-library/blob/master/js/h5p.js#L222-L251
- I'd like the node.js port of H5P core to instantiate H5P content with previously saved states (if set) within the extras argument, cmp. https://github.com/h5p/h5p-php-library/blob/master/js/h5p.js#L929 and https://github.com/h5p/h5p-php-library/blob/master/js/h5p.js#L909 and https://github.com/h5p/h5p-php-library/blob/master/js/h5p.js#L109-L111 and https://github.com/h5p/h5p-php-library/blob/master/js/h5p.js#L97-L105

**Describe alternatives you've considered**
People who want the "save content state" option on their platform could come up with custom solutions to implement in content types, but that would not be efficient on a global scale and defeat the purpose of H5P content being shareable across platforms.

**Comment by sr258** [comment]
Thanks for the detailled list how the PHP implementation does it. This will help making sure we follow the "specification". State support is on the roadmap. If you know anybody who needs it right away:

- You have to change generateIntegration of H5PPlayer and H5PEditor to return the appropriate values to enable state saving.
- You have to implement these endpoints:
```ts
server.post(
        '/h5p/contentUserData/:contentId/:dataType/:subContentId',
        (
            req: express.Request<
                { contentId: string; dataType: string; subContentId: string },
                {},
                H5P.IPostContentUserData
            >,
            res
        ) => {
            res.status(200).send();
        }
    );


    // STUB	    // STUB, not implemented yet. You have to get the user id through a session
    server.get('/h5p/contentUserData', (req, res) => {	    // cookie as h5P does not add it to the request. Alternatively you could add
        res.status(200).send();	    // it to the URL generator.
    });	    server.get(
        '/h5p/contentUserData/:contentId/:dataType/:subContentId',
        (
            req: express.Request<{
                contentId: string;
                dataType: string;
                subContentId: string;
            }>,
            res: express.Response<H5P.IGetContentUserData | {}>
        ) => {
            res.status(200).json({});
        }
    );
```
interfaces:
```ts
export interface IPostContentUserData {
    /**
     * The actual data. 0 if the data should be deleted.
     */
    data: any | 0;
    /**
     * Indicates that data should be invalidated when content changes.
     */
    invalidate: 0 | 1;
    /**
     * Indicates that data should be loaded when content is loaded.
     */
    preload: 0 | 1;
}

export interface IGetContentUserData extends IAjaxResponse {
    data: any;
}
```

**Comment by otacke** [comment]
@sr258 There may actually be interest in contributing the code, but it will rather not be me writing it.

**Comment by ramonziai** [comment]
@otacke That sounded promising, are there any updates on such a contribution? This is an important feature for many people, would be great to have it supported by this (really cool) port.

**Comment by sr258** [comment]
@ramonziai We've funding for the feature and it will probably be finished this year.

**Comment by ramonziai** [comment]
@sr258 Cool, great to hear!

**Comment by otacke** [comment]
@ramonziai The code exists, but for an older version of the node.js port (would need some rewrite to account for some changes that were done since forking) and it is still in review. It's nice though: features both file based and mongo db storage options for the state and uses JWT authentication/authorization to identify the user. The latter is kind of closely tied to the particular platform integration, so this would probably need to be implemented more openly - all the better that Lumi got funding to do it the way they want it right away.

**Comment by ramonziai** [comment]
@otacke Sounds great! Will it also be possible to hook in custom storage for "save content state"? For example, if one wanted to use some RDBMS, or event data stored in a Learning Record Store, or something else?

**Comment by otacke** [comment]
@ramonziai Storing/retrieving is done by implementing an interface, so you could add implementations for other storages easily, yes. But if I was not clear, sorry: The existing code has nothing to do with what Lumi will implement - although I am sure that they'll keep that in mind, too.

**Comment by JPSchellenberg** [comment]
I will start working on it today. You can review/see the progress in PR #1886

**Comment by JPSchellenberg** [comment]
I have a question to how the client handles the contentUserData and hope @otacke or someone else can help me:

There seem to be two ways to initialise the contentUserData:

[1. load preloadedData from content.userContentData](https://github.com/h5p/h5p-php-library/blob/master/js/h5p.js#L2402) 

[2. load data via contentUserDataAjax](https://github.com/h5p/h5p-php-library/blob/master/js/h5p.js#L2424)

When I load the contentUserData via the contentUserDataAjax it does not work. The server responds with an JSON Object with a `data` field which contains the data as string: 

When I provide it as actual JSON Object I get an error at https://github.com/h5p/h5p-php-library/blob/master/js/h5p.js#L2433

Has anyone any hints ? The content type is a Course Presentation with some SingleChoice/MultiChoice and fill in the words.

![Screenshot 2021-11-13 at 22 19 59](https://user-images.githubusercontent.com/9697985/141659380-5dbdfaee-a443-438a-b6d4-64a708db95d5.png)

![Screenshot 2021-11-13 at 22 22 40](https://user-images.githubusercontent.com/9697985/141659440-8fe09234-2c8a-42db-b856-b3a93a1fb555.png)

![Screenshot 2021-11-13 at 22 34 08](https://user-images.githubusercontent.com/9697985/141659665-eb5c158b-5bcf-42cd-bcec-934118fe5874.png)

**Comment by JPSchellenberg** [comment]
And has anyone a php/wordpress instance running where I can test the behaviour of the original implementation?

**Comment by JPSchellenberg** [comment]
Update: If the contentUserData is directly integrated into the H5PIntegration on server side (method 1) it loads the state just fine.

**Comment by sr258** [comment]
Just a guess: Looks like the data is an escaped string when line 2400 is reached and nit a proper JSON object.

I use a local Drupal 7 docker container with inbuilt SQLite. It works very well but is local only. I recommend you spin one up yourself.

**Comment by JPSchellenberg** [comment]
I had the idea with a docker yesterday also. :) 
The Wordpress instance doesn't use the GET request. It provides the contentUserData via the integration object.

The data must be an escaped string because it gets parsed in line 2417. If I provide a proper JSON line 2417 throws an error.

**Comment by sr258** [comment]
If you pass something to the JSON parser it must be a string, but it mustn't be escaped. That might be the problem.

**Comment by JPSchellenberg** [comment]
I tried it, but even a non escaped string does not work..

**Comment by JPSchellenberg** [comment]
Maybe it is bugged, but not noticed by many because as far as I see most integrations put the contentUserData into the Integration object.

**Comment by sr258** [comment]
I don't believe that there's a bug as serious as this in the core. Must be something about how the data is returned.

**Comment by sr258** [comment]
How can I reproduce the issue? Can I simply run the code in the PR?

**Comment by otacke** [comment]
@JPSchellenberg Sorry that I didn't reply earlier. I am currently trying to learn to work less on weekends :-) 

For your case: Have you checked your implementation of the `GET` route for contentUserData? Are you possibly still using the [stub](https://github.com/Lumieducation/H5P-Nodejs-library/blob/3bf9841d42c42905d9163dad743679ecef205e9d/packages/h5p-examples/src/express.ts#L241-L256) that always resolves with `{}` and thus will [lead to `undefined`](https://github.com/h5p/h5p-php-library/blob/22115c0aeaa34faef5109c3f378add2d1647c837/js/h5p.js#L2366-L2368) (no `success` property, no `message` property)?

Beyond that: I am not sure how relevant the `contentUserData` GET route really is for platform integrations. The plugins by Joubel all implement it ([WordPress](https://github.com/h5p/h5p-wordpress-plugin/blob/d9072b6d1b1f40b5b37e9f57e6248ea6851346d9/admin/class-h5p-plugin-admin.php#L1163-L1279), [moodle](https://github.com/h5p/moodle-mod_hvp/blob/9d9e785160541095488b6184223a16b4697745f2/classes/content_user_data.php), [Drupal 7](https://git.drupalcode.org/project/h5p/-/blob/7.x-1.x/h5p.module#L1486-1596), [Drupal 9](https://git.drupalcode.org/project/h5p/-/blob/9.x-1.x-dev/src/Controller/H5PAJAX.php#L120-225)), so one can use it on all of them. Still, all the plugins set the value in H5PIntegration ([WordPress](https://github.com/h5p/h5p-wordpress-plugin/blob/1b4b8b661f7de667af543b7d9a3169efe85aa253/public/class-h5p-plugin.php#L984-L987), [moodle](https://github.com/h5p/moodle-mod_hvp/blob/9d9e785160541095488b6184223a16b4697745f2/classes/view_assets.php#L81-L83), [Drupal 7](https://git.drupalcode.org/project/h5p/-/blob/7.x-1.x/h5p.module#L1106), [Drupal 9](https://git.drupalcode.org/project/h5p/-/blob/9.x-1.x-dev/src/Entity/H5PContent.php#L327)) with a default of `state:  {}`. It's always used and the GET route never kicks in.

And if the route was used here: There is in fact an issue in H5P core. The `H5P.getUserData` function will resolve immediately with the [value of `contentUserData`](https://github.com/h5p/h5p-php-library/blob/22115c0aeaa34faef5109c3f378add2d1647c837/js/h5p.js#L2402) if it is set in the `H5PIntegration` object. However, it does an [AJAX call](https://github.com/h5p/h5p-php-library/blob/master/js/h5p.js#L2416) otherwise and in turn `H5P.getUserData` will not return the return the previous state before the AJAX call is resolved.

If you now check https://github.com/h5p/h5p-php-library/blob/22115c0aeaa34faef5109c3f378add2d1647c837/js/h5p.js#L107-L137 you'll notice that the previous state may still be undefined when the `H5P.newRunnable` function is called, because `library.userDatas` is set asynchronously by the `H5P.getUserData` function.

**Comment by JPSchellenberg** [comment]
> @JPSchellenberg Sorry that I didn't reply earlier. I am currently trying to learn to work less on weekends :-)

That's how it should be! :D

`H5P.newRunnable` is run before the requests resolves and I guess therefore the previousState set in the callback has no effect on the already instanced H5P. Is this correct? I think you wrote this here https://github.com/h5p/h5p-php-library/issues/112 also, if I understood it correctly.

**Comment by JPSchellenberg** [comment]
> How can I reproduce the issue? Can I simply run the code in the PR?

I will prepare the PR so you can test it, but keep in mind that it will be just a work in progress. I will delete the `contentUserDataStorage.ts` from the examples later.

**Comment by otacke** [comment]
@JPSchellenberg
> `H5P.newRunnable` is run before the requests resolves and I guess therefore the previousState set in the callback has no effect on the already instanced H5P. Is this correct? I think you wrote this here [h5p/h5p-php-library#112](https://github.com/h5p/h5p-php-library/issues/112) also, if I understood it correctly.

Exactly, that's the reason why the previous state would not be set for a content type if you leave out the `contentUserData` property in `H5PIntegration`. H5P core would try to get the state via the `contentUserData` route, but the response would be too late for content instantiation in `H5P.newRunnable`.

Still, it might be worth to check the GET route itself (e.g. calling it in the browser with valid parameters directly). It might not return a JSON object the way that H5P expects it.

**Comment by JPSchellenberg** [comment]
@sr258 I added a commit where you can test the behaviour: https://github.com/Lumieducation/H5P-Nodejs-library/pull/1886/commits/ccce7a61e7389f1e5a158574dc59313ff1eb5d2c

@otacke The structure of the returned object is
```json
{
    data: "{"progress":2,"answers":[[["Norway"]],[{"progress":0,"answers":{"corrects":0,"wrongs":0}}],[{"answers":[]}],[[]]],"answered":[false,false,false,true]}"
}
```
 and as far as I figured it out that should be the correct format, but I might be wrong as my understanding of the client side of H5P is very limited. :)

**Comment by otacke** [comment]
@JPSchellenberg Close. The response should match the AJAX response interface definition that's defined at https://github.com/Lumieducation/H5P-Nodejs-library/blob/master/packages/h5p-server/src/types.ts#L23-L51

You're lacking the `success` property, so H5P core will assume the request failed and expect the `message` property for more information. As mentioned before, this will give you `undefined` (the value of `response.message`) (https://github.com/h5p/h5p-php-library/blob/22115c0aeaa34faef5109c3f378add2d1647c837/js/h5p.js#L2366-L2368).

**Comment by JPSchellenberg** [comment]
I tried your suggestion, but it still does not work. So I think it is really that `H5P.newRunnable` is run too early.

**Comment by otacke** [comment]
@JPSchellenberg Oh, sorry, I thought I made that clear! It will definitely not work without setting `contentUserData` in `H5PIntegration` because of that issue in H5P core. Still, I was under the assumption that you wanted to implement the `GET` route properly.

**Comment by JPSchellenberg** [comment]
No, it was pretty clear that it won't work. I just wanted to make sure and give a feedback. :)

The question is if we want to implement something that does not really work (and is probably never called/used).
@sr258 @otacke What do you think? Should we leave that out until it is fixed in the H5P core?
I would at least make the implementation in the interface optional.

**Comment by otacke** [comment]
@JPSchellenberg I really don't know if that function is relevant (see initial comment). It doesn't seem to be used for anything except for the broken "fallback", so I assume it could be left out - if it turns out it will be used for something, it could be added easily later on. I'll reach out to Joubel in order to get some more information.

**Comment by otacke** [comment]
@JPSchellenberg Doh, I should have checked the editor first. It is actually used (https://github.com/h5p/h5p-editor-php-library/blob/7bc192798f8f6e1dee34891b56f3bf60ab320f3d/scripts/h5peditor.js#L1471) - for storing the state of wizards having run, for instance.

**Comment by JPSchellenberg** [comment]
@otacke Alright. Thank you very much! Then I will implement it.
