### ISSUE TITLE
Assets not included in build directory

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#106]
Currently, several files are not added to the build folder, but I think they're required if the package is included somewhere else:

src/schemas (JSON validator schemas)
src/client (don't know what this is)
src/translations (translation strings for our core)

They must but copied over. Maybe we should move these files to some special (assets) folder that is copied over when the project is built?

**Comment by JPSchellenberg** [comment]
`src/client` contains the client-side implementation for the Editor and should be removed from `src/` as it is an implementation.
We could run a simple copy-script in the `npm run build` command. What do you think?
