### ISSUE TITLE
npm not found

### ISSUE THREAD

**Issue by arashsoftco** [Lumieducation/H5P-Nodejs-library#1068]
hi
h5p-react
h5p-webcomponents
and other .....
is not in npm
also 
https://github.com/Lumieducation/H5P-Nodejs-library/blob/HEAD/examples/
this example for express js

**Comment by JPSchellenberg** [comment]
This is because these packages are still marked as private. I will make them public shortly.

**Comment by JPSchellenberg** [comment]
The packages should be public now.

**Comment by arashsoftco** [comment]
@JPSchellenberg 
hi thanks 
would you please help me with this i got 404 https://github.com/Lumieducation/H5P-Nodejs-library/blob/HEAD/examples/
i also doesn't have access to 
https://github.com/Lumieducation/h5p-rest-example
i want to start h5p with nodejs serve and mongodb and react 
is this rep help me?(https://github.com/Lumieducation/H5P-Nodejs-library/)
