### ISSUE TITLE
h5p rest

### ISSUE THREAD

**Issue by arashsoftco** [Lumieducation/H5P-Nodejs-library#1072]
hi 
would you please help me with this i got 404 https://github.com/Lumieducation/H5P-Nodejs-library/blob/HEAD/examples/ 
(as you said here
 https://www.npmjs.com/package/h5p-nodejs-libraryAn example of how to integrate and use this library with Express can be found in examples.)
 
i also doesn't have access to

https://github.com/Lumieducation/h5p-rest-example

i want to start h5p with nodejs serve and mongodb and react
is this rep help me?(https://github.com/Lumieducation/H5P-Nodejs-library/) because i did not find out correctly no readme in git

**Comment by sr258** [comment]
Hi @arashsoftco . We're somewhere at the end of a big restructuring of the whole project to make it more maintainable. While we used to only have h5p-nodejs-library, we now have a monorepo (this repo), which includes several packages:
@lumieducation/h5p-server (the core package)
@lumieducation/h5p-mongos3 (db support for mongo & s3)
@lumieducation/h5p-express (routers for Express)
@lumieducation/h5p-html-exporter (used by the Lumi desktop app to create standalone html bundles)
@lumieducation/h5p-webcomponents (a drop-in component that can be used to display the editor and the player in any HTML page)
@lumieducation/h5p-react (a drop-in in component wrapping around the web components for React)
@lumieducation/h5p-example (the sever-side-rendering example; check it out here: https://github.com/Lumieducation/H5P-
Nodejs-library/tree/master/packages/h5p-examples)
soon to be released: @lumieducation/h5p-rest-example (You've found the private repo for this and we had to keep this private for contractual reasons until now). The h5p-rest-example is probably close to what you need (it uses React and Express). You can already peek into it in the branch of this PR: https://github.com/Lumieducation/H5P-Nodejs-library/pull/1045 It will be merged soon.

**Comment by arashsoftco** [comment]
thanks 
so now can i use 
@lumieducation/h5p-server 
@lumieducation/h5p-mongos3 
@lumieducation/h5p-express 
@lumieducation/h5p-react

or they are not working yet?

**Comment by sr258** [comment]
They should work fine. The documentation is still out of date, as the components are in different places now and must be imported differently. The API itself hasn't changed much.

**Comment by arashsoftco** [comment]
because i got this problem while npm i on h5p react:

```
arash@arash-itosoft:~/Desktop/h5p/git/v702/packages/h5p-react$ npm i

> @lumieducation/h5p-react@7.0.1 prepare /home/arash/Desktop/h5p/git/v702/packages/h5p-react
> npm run build


> @lumieducation/h5p-react@7.0.1 build /home/arash/Desktop/h5p/git/v702/packages/h5p-react
> npx tsc --build tsconfig.es2015.json && npx tsc --build tsconfig.umd.json

npx: installed 1 in 2.755s
error TS5023: Unknown compiler option 'build'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @lumieducation/h5p-react@7.0.1 build: `npx tsc --build tsconfig.es2015.json && npx tsc --build tsconfig.umd.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @lumieducation/h5p-react@7.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arash/.npm/_logs/2021-02-19T07_10_53_087Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @lumieducation/h5p-react@7.0.1 prepare: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @lumieducation/h5p-react@7.0.1 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arash/.npm/_logs/2021-02-19T07_10_53_173Z-debug.log

```

**Comment by JPSchellenberg** [comment]
This problem occurs when you run `npm run build` within the package. As the typescript dependency is a shared dependency across all packages it is installed in the root folder.
Try changing to the project root and run `npm run build:h5p-react`. That should build the h5p-react package correctly.

**Comment by sr258** [comment]
Also, I would recommend using the packages from NPM directly: https://www.npmjs.com/package/@lumieducation/h5p-react

**Comment by sr258** [comment]
@arashsoftco  I've restructured the documentation and you can check out the current draft in https://docs.lumi.education/v/docs%2Fstructure/ if you need to get going soon.

**Comment by arashsoftco** [comment]
@sr258 Thank you for your kindness

**Comment by sr258** [comment]
@arashsoftco Can we still help you out here? If not, I'll close the issue soon.

**Comment by arashsoftco** [comment]
hi i can not still install new version 
```
lerna ERR! npm install exited 1 in '@lumieducation/h5p-examples'
lerna ERR! npm install stdout:

> puppeteer@7.1.0 install /home/arash/Desktop/h5p/github/packages/h5p-examples/node_modules/puppeteer
> node install.js


lerna ERR! npm install stderr:
ERROR: Failed to set up Chromium r848005! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@7.1.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@7.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arash/.npm/_logs/2021-02-25T16_11_46_331Z-debug.log

lerna ERR! npm install exited 1 in '@lumieducation/h5p-examples'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @lumieducation/h5p-monorepo@7.0.1 postinstall: `npx lerna bootstrap && npm run download:content-type-cache && npm run download:h5p`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @lumieducation/h5p-monorepo@7.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arash/.npm/_logs/2021-02-25T16_11_46_503Z-debug.log
arash@arash-itosoft:~/Desktop/h5p/github$ 

```
