### ISSUE TITLE
CMS as target for development

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#108]
It would be useful to identify potential content management systems or learning management systems that might be candidates for an implementation. If we develop the library without a reality check there is a risk that the interfaces we provide are not suitable for real life usage.

**Comment by JPSchellenberg** [comment]
I think @jankapunkt is currently implementing it in their cms. He can give us feedback and I will ask some people that I know want to implement it if they can support us.

**Comment by dailez** [comment]
I just started using and testing the h5p-editor library for my project based on [Sails.js](https://sailsjs.com/). So more feedback will come soon. However, what I figured out recently is that the way the image upload works does not fit to Sails.js (it uses [skipper](https://github.com/balderdashy/skipper) for file uploads). An exception handling in the middleware for the some routes (/ajax?action=files' and '/ajax?action=library-upload') was needed.

**Comment by sr258** [comment]
Ok, I think having two cms implementations is fine!

**Comment by jankapunkt** [comment]
Our CMS is very customized and you may rather check on other popular NodeJS CMS out there:

https://github.com/hexojs/hexo

https://github.com/TryGhost/Ghost

https://github.com/strapi/strapi

https://github.com/keystonejs/keystone

**Comment by JPSchellenberg** [comment]
We do not want to implement it into a CMS, but rather have some people report back to us on what is needed to implement this library. So if we know about some people using this library and these people open issues here it is all we ask for. :)
