### ISSUE TITLE
Merge H5P-Demo back into this repository

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/H5P-Nodejs-library#110]
Hey,

I am a fan of mono-repositories and as we are thinking about merging the player into this repository (#55 ) I also would like to merge the examples and smoke tests, so we can run them on our ci-service and have everything in one place.
At the moment it is only possible to run these tests by publishing to npm and inserting the new version into the H5P-Demo repository, which is not a nice way to do.

( see also https://github.com/Lumieducation/H5P-Player-Nodejs-library/issues/77)

**Comment by sr258** [comment]
I agree that this greatly simplifies development. The should be the only implementation in the repository, though, and only do basic things. The future electron app should have its own project.
