### ISSUE TITLE
Zip archive error while uploading a valid H5P file

### ISSUE THREAD

**Issue by 0xMurage** [Lumieducation/H5P-Nodejs-library#1102]
I am trying to upload a H5P zip file example from [H5P site](https://h5p.org/presentation) but I am having an error during the unzip process. Installing libraries, and uploading files work all fine. I have tested the validity of the zip file in other editors and it uploads and extracts everything as expected.

My server-side setup uses [Express](https://expressjs.com/) that implements the `H5PAjaxEndpoint.postAjax ` method.  I am using express-fileupload middleware to handle file uploads. The content, library, and temporary storages are on a local disk.

Here is the error when I try to debug
![error](https://user-images.githubusercontent.com/25152892/109123623-1d2ab700-775b-11eb-9915-91096554a063.png)
 of the temp file

the MD5 sum of the temp zip file

![temp md5-sum](https://user-images.githubusercontent.com/25152892/109123666-24ea5b80-775b-11eb-87a3-56a48fb0e982.png)

the Express file upload middle setup (using memory for temporary uploads doesn't have effect for this case)

```
app.use(fileUpload({
    limits: {fileSize: 500},
    useTempFiles: true,
    tempFileDir: tmp.dirSync({keep: false, unsafeCleanup: true}).name
}));
```

**Comment by sr258** [comment]
Does the file upload work in the examples provided in the repository?
Can you provide the file so that we can check on our end what's wrong?

**Comment by sr258** [comment]
Is the file size limit in megabytes? It might be in bytes and the file could be cut off because of it.

**Comment by 0xMurage** [comment]
thank you @sr258. I had overlooked the file size. I had overlooked the `express-fileupload` middleware  file size limits. [Busybox](https://github.com/mscdex/busboy#busboy-methods) file size is in `bytes` format and I had assumed it was in `mega bytes`.
