### ISSUE TITLE
dependency did not install well node 12.18.0 lts

### ISSUE THREAD

**Issue by arashsoftco** [Lumieducation/H5P-Nodejs-library#1107]
hi i trying to run project on node 12.18.0 lts as i faced problem in #1106 with node 14.15 lts

root@bisotuntech:~/h5p/H5P-Nodejs-library/H5P-Nodejs-library# ls
CHANGELOG.md          docs                        lerna.json         release.config.js  tsconfig.json
LICENSE               jest.config.js              package-lock.json  renovate.json      tslint.json
code-of-conduct.md    jest.db.config.js           package.json       scripts
commitlint.config.js  jest.integration.config.js  packages           test
root@bisotuntech:~/h5p/H5P-Nodejs-library/H5P-Nodejs-library# sudo npm i

> husky@4.3.6 install /root/h5p/H5P-Nodejs-library/H5P-Nodejs-library/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> puppeteer@7.1.0 install /root/h5p/H5P-Nodejs-library/H5P-Nodejs-library/node_modules/puppeteer
> node install.js

Downloading Chromium r848005 - 138.2 Mb [====================] 100% 0.0s 
Chromium (848005) downloaded to /root/h5p/H5P-Nodejs-library/H5P-Nodejs-library/node_modules/puppeteer/.local-chromium/linux-848005

> core-js@3.9.0 postinstall /root/h5p/H5P-Nodejs-library/H5P-Nodejs-library/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> husky@4.3.6 postinstall /root/h5p/H5P-Nodejs-library/H5P-Nodejs-library/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

npm WARN lifecycle @lumieducation/h5p-monorepo@7.0.1~postinstall: cannot run in wd @lumieducation/h5p-monorepo@7.0.1 npx lerna bootstrap && npm run download:content-type-cache && npm run download:h5p (wd=/root/h5p/H5P-Nodejs-library/H5P-Nodejs-library)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2050 packages from 1324 contributors and audited 2027 packages in 46.33s

112 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
root@bisotuntech:~/h5p/H5P-Nodejs-library/H5P-Nodejs-library# npm start

> @lumieducation/h5p-monorepo@7.0.1 start /root/h5p/H5P-Nodejs-library/H5P-Nodejs-library
> npm run start --prefix packages/h5p-examples

> @lumieducation/h5p-examples@7.1.0 start /root/h5p/H5P-Nodejs-library/H5P-Nodejs-library/packages/h5p-examples
> CACHE=in-memory node build/express.js

internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module '/root/h5p/H5P-Nodejs-library/H5P-Nodejs-library/packages/h5p-examples/build/express.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @lumieducation/h5p-examples@7.1.0 start: `CACHE=in-memory node build/express.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @lumieducation/h5p-examples@7.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-25T19_31_07_644Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @lumieducation/h5p-monorepo@7.0.1 start: `npm run start --prefix packages/h5p-examples`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @lumieducation/h5p-monorepo@7.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-25T19_31_07_677Z-debug.log

**Comment by sr258** [comment]
Solved in https://github.com/Lumieducation/H5P-Nodejs-library/issues/1106
