### ISSUE TITLE
customise a content

### ISSUE THREAD

**Issue by arashsoftco** [Lumieducation/H5P-Nodejs-library#1111]
hi how can i customize h5p content like this part

[https://pasteboard.co/JQ7mffX.png](url)

i searched in files but nothing 

forexample:this div in interactive video editor
`
<input class="h5peditor-text" type="text" id="field-duration-154" value="0:00" placeholder="From" maxlength="15">`

**Comment by sr258** [comment]
What exactly do you want to customize? Customizing styles with CSS is relatively "easy": You have to add a CSS file to your project. Then you add it to the list of styles as described in the [documentation page on customization](https://docs.lumi.education/advanced-usage/customization). You can either add it globally or only for specific libraries. Check out the docs page for details.

If you want to customize the behavior of libraries, this is more complex. You can either append or replace scripts with the hooks (described in the docs above) or you'll have to fork the library you want to modify and upload it under a different name.

**Comment by arashsoftco** [comment]
well not actually changes behavior for example insted of input url for action click  i want user to select url from a selection div

**Comment by sr258** [comment]
To achieve this you must modify the JavaScript code of H5PEditor.InteractiveVideo: https://github.com/h5p/h5p-editor-interactive-video

You can then either simply upload your forked library like a normal library or you can try replacing the modified files with the hooks I mentioned. Then you won't have to fork the library, but you will still have to worry about changes in the upstream library...
