### ISSUE TITLE
Place to check access rights

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#112]
Where do we want to check if a user has the permission to perform an operation. For example, where do we check if a user has the permission to download a piece of content. Is this done in the exporting function or is the exporting function unaware who is calling it and the permissions check are done e.g. by the implementation?

**Comment by JPSchellenberg** [comment]
I would strongly advocate for letting user permission up to the implementation. I don't see a reason to do it in the library or am I missing something?

**Comment by sr258** [comment]
Well, who has which permissions must obviously come from the implementation, but the library could check if users are actually allowed to do an action on its own, e.g. like here: https://github.com/Lumieducation/H5P-Editor-Nodejs-library/blob/a90d8de33413845ae0b56cd09fd462e5458a7a90/src/PackageManager.ts#L120

It might be possible to completely keep the library free from permissions and fully handle them before the library is called, but this would mean that the implementation has to call very specific methods in some cases. Consider this second example:

When a user uploads a package, the library must know whether the user has privileges to install libraries. One way of approaching this would be to simply call the library method and the library inquires which privileges the user has and acts accordingly (installs libraries or checks if the content can be used without installing it). An alternative would be to leave the check to the implementation and provide to methods: uploadPackageAndInstallLibraries(...) and uploadPackageWithoutInstallingLibraries(...).

After writing this, I think the library should be able to check what permissions a user has to not overcomplicate things for the implementation.

**Comment by jankapunkt** [comment]
I would really like to continue to check permissions on the implementation level. For me it would be more complicated if  I have also consider module-specific permissions in addition to those within my application.
