### ISSUE TITLE
Provision for a user to override the static content & ajax endpoints

### ISSUE THREAD

**Issue by 0xMurage** [Lumieducation/H5P-Nodejs-library#1139]
Can we provide a way for a user to override the ajax and full static content endpoints relative URL in the config. 
I have a scenario where I am serving the **static content** (libraries, core, editor, & content) under different relative url as that of **ajax** endpoints.

Currently I am overriding the UrlGenerator static content file `baseUrl` but should this be supported out of the box?

**Comment by sr258** [comment]
I think we already support this:

You can set these configuration values in the config: 
- ajaxUrl (updated this on 4th March 12:05)
- baseUrl
- contentUserDataUrl
- coreUrl
- downloadUrl
- editorLibraryUrl
- librariesUrl
- paramsUrl
- playUrl
- setFinishedUrl
- temporaryFilesUrl

You are probably looking for `librariesUrl`, `coreUrl` and `editorLibraryUrl`. By changing these config values you can change the route relative to `baseUrl`. If you want to make them available at a completely different route (e.g. on a different host), you can create your own implementation of `IUrlGenerator` or extend the existing [`UrlGenerator`](https://github.com/Lumieducation/H5P-Nodejs-library/blob/master/packages/h5p-server/src/UrlGenerator.ts). You can pass any IURLGenerator into the constructors of `H5PPlayer` and `H5PEditor` to override the default one.

Content files can also be served from elsewhere by setting the configuration value `contentFilesUrlPlayerOverride`. Here's the documentation on it:
```ts
 /**
     * Base path for content files (e.g. images) IN THE PLAYER. It MUST direct
     * to a URL at which the content files for THE CONTENT BEING DISPLAYED must
     * be accessible. This means it must include the contentId of the object!
     * You can insert the contentId using the placeholder {{contentId}}.
     *
     * Example:
     * http://127.0.0.1:9000/s3bucket/{{contentId}}`
     *
     * You can use this URL to load content files from a different server, e.g.
     * S3 storage. Note that this only work for the player and not the editor.
     */
    contentFilesUrlPlayerOverride: string;
```
It's important to note that this will **not** work in the editor, as Joubel's H5P Editor code constructs its own urls and it uses the `baseUrl + '/content/' + contentId` as a pattern. There's nothing we can do about it at our end.

Does this fit your needs? If not, can you elaborate on your use case?

Note: I've noticed that contentFilesUrlPlayerOverride should be part of the functionality of IUrlGenerator. I've created an issue for it here: https://github.com/Lumieducation/H5P-Nodejs-library/issues/1141

**Comment by 0xMurage** [comment]
that is pretty close. In my case, an editor and a player are generated on the client-side using the awesome web-component package. If I am using Express and I have all ajax endpoints (for both H5P and other application related) served under `/api/v1/h5p `, this would mean if I want to serve the libraries, content, editor, and core files statically, I would then have to place them inside `/api/v1/h5p`  folder which is a bit weird hack.

For now, I have overridden the `UrlGenerator` methods and everything works just fine. I feel this can be made a bit simpler through the config.

**Comment by sr258** [comment]
Ok, I see! Your use case makes total sense. 

Maybe it is enough if you use an empty `baseUrl`. You can then set the other urls to absolute paths, e.g. `ajaxUrl` to `/api/v1/h5p` and `editorLibraryUrl` to `/assets/core/editor`. That way you have full control over all urls without overriding the `UrlGenerator`. I'm not 100% sure if Joubel's H5P client does its own weird things with the baseUrl (it is part of the integration object passed to it), but our code should work in a configuration like this (except for the HTMLExporter, it assumes certains routes).

I'll leave this issue open until I've checked if using an empty `baseUrl` works without issues.
