### ISSUE TITLE
can not uploaded a forked library

### ISSUE THREAD

**Issue by arashsoftco** [Lumieducation/H5P-Nodejs-library#1183]
hi i just want to edit some part of h5p interactive video 
i clone this rep:
https://github.com/h5p/h5p-interactive-video
then edit some part just semantics part
and then pack it with h5p cli 

arash@arash-bisotuntech:~/Desktop/screenlike$ h5p pack -r h5p-interactive-video-master aPacking 1 library to file...
h5p-interactive-video-master OK 1.22.4

files uploaded here:
https://germancdn.abrito.ir/s/aitNiXDgM9odqbs

and upload to h5p nodejs library 
but it stuck at Loading installed libraries from REST endpoint ...

**Comment by sr258** [comment]
This is partly a bug, as the library list should still load even if libraries are missing.

But the main problem is that you need to include all the dependencies of the interactive video in the .h5p package. Check out what a normal h5p file with an interactive video contains. There are dozens of libraries you need to include.

**Comment by arashsoftco** [comment]
did you try the link i have sent?
alll i change to the library is 

```
{
  "semantics": [
    {
      "label": "Interactive Video Editor",
      "fields": [
        {
          "label": "Upload/embed video",
          "fields": [
            {
              "label": "اضافه کردن ویدیو",
              "description": "ویدیو خود را در این بخش اپلود کنید شما میتوانید برای عملکرد بهتر فرمت های متفاوت اپلود کنید"
            },
            {
              "label": "Start screen options (unsupported for YouTube videos)",
              "fields": [
                {
                  "label": "The title of this interactive video",
                  "default": "Interactive Video",
                  "description": "Used in summaries, statistics etc."
                },
                {


```
2 translation

**Comment by sr258** [comment]
Yes, I did.
But if you don't include all the libraries that are needed by the interactive video, it won't work. You need to look into a original .h5p file of an interactive video and also include all the other libraries.

As you only change the localization, it would be better to localize the library with the language files in `language/`.

**Comment by sr258** [comment]
Alternatively you can also install the regular content type from the hub first and then upload your patched version. Then all the dependencies are already installed. You must increase the patch version of your forked library, however!

**Comment by arashsoftco** [comment]
i guess patching is better work thanks i will try out
