### ISSUE TITLE
Check Library interfaces

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#119]
I think the library interfaces right now mix information that is received from the H5P Hub and that is taken from library.json. Sadly, the formats are not exactly the same. The format that is used in library.json is already specified in library-schema.json and should be the one that is used in ILibraryJson. The format we get from the hub is the one in the Library class.

We should also use more telling names like ILibraryJson, HubLibrary and a clearer one for ILibraryData (can't think of one right now).

**Comment by sr258** [comment]
I've created a list of terminology [here](https://github.com/Lumieducation/H5P-Nodejs-library/wiki/Use-of-terminology). In particular, I want to clarify terminology concerning libraries, but maybe also other usages.

@JPSchellenberg Could you have a look at the list and comment on it / change it?

**Comment by sr258** [comment]
@JPSchellenberg Should we split the types.ts file into two: one for types that need to be implemented by an implementation and one that is "internal" (even if objects of these types might be passed to the implementation through return values, or if the implementation needs to pass them as arguments to methods)?

That way we would ease implementation and could simply give a reference to this .ts file instead of repeating the interfaces in the documentation.

**Comment by JPSchellenberg** [comment]
Yeah. That sounds good. 
> @JPSchellenberg Could you have a look at the list and comment on it / change it?

I will have a look at it.
