### ISSUE TITLE
Final goal of this project

### ISSUE THREAD

**Issue by Kasanias** [Lumieducation/H5P-Nodejs-library#12]
Hey there! 

I'm looking to add H5P features to one of my projects and I came across this repo. So I was wondering what are you trying to achieve ? I've seen that you can already embed H5P content.

Cheers!

**Comment by JPSchellenberg** [comment]
Hi,
thank you for your interest.

Steps already achieved:
- [x] upload .h5p files, extract their data and save the data via the provided [interface](https://github.com/Lumieducation/h5p-nodejs-library/blob/master/src/types.d.ts#L6)
- [x] display uploaded .h5p content by resolving [dependencies](https://github.com/Lumieducation/h5p-nodejs-library/blob/master/src/router.ts#L98) and building a page that can be embeded via iframe.

The next step would be to get the editor working.
I am currently working on it, but it is a very "try and error"-way, so it is hard to tell the next steps. You can view the branch here: https://github.com/Lumieducation/h5p-nodejs-library/tree/editor
One step would be to replace the hard-coded [content-type-cache](https://github.com/Lumieducation/h5p-nodejs-library/blob/editor/src/router.ts#L101) 
Another step is to figure out how to save the data from the editor via post to the server. (The Wordpress-Plugin uses a form, but I don't understand it yet.)
I will try to work out a roadmap this weekend and post it here as issues and milestones.

Cheers!

**Comment by JPSchellenberg** [comment]
Hey,
I created a GitHub-Project for the [Editor](https://github.com/Lumieducation/h5p-nodejs-library/projects/1), where you can track the status of this project and also added a [milestone](https://github.com/Lumieducation/h5p-nodejs-library/milestone/1). At the moment, the display and upload of H5P-Content seem to work fine for me. Please let me know if you encounter any bugs or need help in setting up the development environment.

**Comment by JPSchellenberg** [comment]
Hey,

after restructuring the project, we separated the H5P-Viewer and the [H5P-Editor](https://github.com/Lumieducation/H5P-Editor-Nodejs-library). 

This repository will host the H5P-Viewer, a function that takes H5P-Data and builds a string, which can be served as HTML-Page and embedded via iframe. We made this decision to be framework-agnostic and dependency-free.
We released the first, experimental version of it today. Please read the [instructions](https://github.com/Lumieducation/H5P-Nodejs-library#how-to-use), feel free to try it and provide us with feedback if you got it working.

I am looking forward to your feedback.

**Comment by rtens** [comment]
Closing this issue since I regard the question as answered. Please re-open if that's not the case.
