### ISSUE TITLE
Implement installLibrary

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/H5P-Nodejs-library#12]

**Comment by sr258** [comment]
I've looked into the code of the PHP implementation and installing libraries does the following:

1. Check token (see #25)
1. Check machine name (empty)
2. Check if machine name is part of hub (by checking in content type cache)
3. Check if user can install this specific content type
4. Download content type from Hub (by downloading from .../content-types/H5P.Example)
5. Validate package (H5P-PHP-library: H5PValidator->isValidPackage)
6. Store package (H5P-PHP-library: H5PStorage->savePackage)
7. Remove temporary files

The H5PStorage.savePackage function is also reused when uploading H5P packages with actual content, so implementing the installation will also advance uploading packages in general a lot. The whole process is pretty complex, though! What's next on your agenda?

The more and more I look at the H5P server core code, the more I get the impression that it's not a good idea to follow the structure of the PHP implementation! It seems to suffer from technical debt and isn't object oriented to a large extend (or mostly actually). Everything is in very few mega classes that do many unrelated things and the methods in those classes are sometimes very long and could be split up to make them easier to understand. 

Have you thought about how the architecture of the Node implementation should look like? Even though this might be difficult at the moment without having fully understood everything that the PHP implementation does, but I really think it would be good if there were a few sketches of the basic building blocks of the future application.

**Comment by JPSchellenberg** [comment]
Ups. I have missed this comment. Sorry for answering so late. This one will be next on our agenda. The PHP implementation definitely suffers from technical debt and we should use our advantage to write code from scratch. I have not thought about the architecture as my approach till now was more like a 'try and error'-way by just replicating the server responses from the WordPress-plugin as I could not get my head around the php-code. (I don't know any php). And as I worked step by step I have no overview of what else the php-library does.

If you have any ideas I would be more than happy to hear them. Otherwise, we could have a brainstorm with @rtens .

**Comment by JPSchellenberg** [comment]
@sr258 is there something we can do to help you with the validator?

**Comment by sr258** [comment]
I‘ll integrate it into the editor today and create a pull request. It would be great if your reviewed it then. It has become pretty long (but the PHP validator is long and complex, too). You can check out the validator here: https://github.com/sr258/H5P-Extractor/tree/validator

**Comment by sr258** [comment]
I've put the validator into the editor and create a branch for this: https://github.com/sr258/H5P-Editor-Nodejs-library/tree/hub-install
Right now the validator is not referenced or used anywhere except for the tests. The next steps would be:

1) Add tests that test the validator with every H5P file in the hub and fix errors.
2) implement installing libraries from the hub.

If you want to help out with the validator, it'd be great if you wrote tests that are similar to the ones you've created for the viewer (those that scrape h5p.org and then download the h5p files to display them).I'd proceed with installing the libraries from the hub.

**Comment by JPSchellenberg** [comment]
Alright. I would suggest opening a PR, give it the label "[status] in progress" and I will add the tests there.

**Comment by sr258** [comment]
I've created a draft PR [here](https://github.com/Lumieducation/H5P-Editor-Nodejs-library/pull/50#issue-305442272). I can't assign labels, but the draft mode should make it's status clear.

**Comment by rtens** [comment]
@sr258 Would love to join the effort with implementing installLibraries. Are you gonna work on that this weekend? If not, how can I be of assistance?

**Comment by sr258** [comment]
@rtens If you want to pick it up here, you could continue in ContentTypeInformationRepostory.install. I'm currently working in a branch that has a PR here: https://github.com/Lumieducation/H5P-Editor-Nodejs-library/pull/50

Steps 2-4 from above are finished. What's still missing is 5-8. They would mostly have to be done in LibraryManager and FileLibraryStorage. I only have an hour or so today and a few tomorrow, so you could probably even finish the installation process this weekend. I would then continue working on the validator in the meantime.

**Comment by rtens** [comment]
Alright great. I'll get working on steps 5, 7 and 8 then, basing in on the hub-install branch.

**Comment by rtens** [comment]
Update: I got held up by #52 but am getting to it now. In [this branch](https://github.com/Lumieducation/H5P-Editor-Nodejs-library/tree/add/12-install-libraries).

**Comment by rtens** [comment]
Since the bare-bone version turned out to be a pretty small change, I based [the branch](#54) on master in the end.

**Comment by rtens** [comment]
Added uploading packages and editing the uploaded content. But I realized that images are not displayed. H5P.org seems to store content files globally (e.g. [this one](https://h5p.org/sites/default/files/h5peditor/images/imageSlideBackground-56c5a34a4470f.jpg)) and not per-content. So maybe we need to do that as well but it feels weird.

**Comment by sr258** [comment]
@rtens Should I continue with the proper implementation of the installation process then?

**Comment by rtens** [comment]
Definitely. What exactly do you mean by "proper"? I assume steps 1-4 and 6?

Let me know if you need support merging my commits.

**Comment by sr258** [comment]
Yes, all the other steps and integrating it into the rest of the framework. The other steps will need to have to access the ContentTypeRepository, the TranslationService, the LibraryManager etc. I'll get going on this then.

**Comment by JPSchellenberg** [comment]
> Added uploading packages and editing the uploaded content. But I realized that images are not displayed. H5P.org seems to store content files globally (e.g. [this one](https://h5p.org/sites/default/files/h5peditor/images/imageSlideBackground-56c5a34a4470f.jpg)) and not per-content. So maybe we need to do that as well but it feels weird.

I think only H5P.org does it that way. The WordPress example stores the images per-content. Images usually within an `images/`-folder. The path is stored within the `content.json` and the is prepended with the [filesPath](https://github.com/Lumieducation/H5P-Editor-Nodejs-library/blob/master/src/index.js#L20). We just have to get this right.

**Comment by rtens** [comment]
I consider this issue closed. Re-open if not.
