### ISSUE TITLE
H5P Reactjs build: api call to  h5p/core/js/jquery.js?version=1.24.0 -  pending issue

### ISSUE THREAD

**Issue by Progressive-Programmer** [Lumieducation/H5P-Nodejs-library#1398]
### H5P Reactjs build: Api call to  [.../h5p/core/js/jquery.js?version=1.24.0 ](url)-  pending issue

After React build and deployed 
on H5P create new the hub doesn't load. 

This issue is not in the development stage. 

<img width="1440" alt="Screenshot 2021-05-11 at 9 43 28 AM" src="https://user-images.githubusercontent.com/25490780/117758982-9c9b3300-b240-11eb-833b-afa3daf4bd54.png">

**Comment by sr258** [comment]
Do the other H5P files load properly? Try disabling the browser cache to get a more complete picture whether they load. How is your development stage different from the production one? What is you NodeJS version? How do you serve the static files? Can you reproduce the issue in the rest example so that I can test on my end?

**Comment by Progressive-Programmer** [comment]
Disabled the cache, all other files load. 

Nodejs version: v14.15.3

I have the component from **h5p-rest-example-client**  and there folders `Services` and `Components ` in my project 
in src/App.tsx
  `                    <ContentListComponent
                        contentService={this.contentService}
                    ></ContentListComponent>`

In development : the call to `/h5p/core/js/jquery.js` completes like in the picture 


<img width="1440" alt="Screenshot 2021-05-11 at 10 56 23 AM" src="https://user-images.githubusercontent.com/25490780/117763019-b7bd7100-b247-11eb-9c4a-2e19c3eae696.png">

But after  : npm run build  & deployed the 

<img width="1440" alt="Screenshot 2021-05-11 at 10 50 01 AM" src="https://user-images.githubusercontent.com/25490780/117763096-db80b700-b247-11eb-8025-364211a82154.png">

**Comment by sr258** [comment]
Does your distribution package really include the jquery.js file? Maybe it wasn't copied over for some reason...

How does your production setup look like exactly and how is different from dev mode? So how do you serve the static files generated by build and how do you proxy the backend? Without this information, I can't really reproduce the issue here.

Can you check the logs of the backend (and if you have them all reverse proxies) whether the request for jquery.js ever reaches it? Also try turning on the debug mode by calling the backend with `DEBUG=h5p* LOG_LEVEL=debug` and look for the request and see why it fails.

**Comment by spsinghats** [comment]
How do I setup the DEBUG=h5p* and LOG_LEVEL=debug on my server @sr258

**Comment by Progressive-Programmer** [comment]
https://github.com/Lumieducation/H5P-Nodejs-library/issues/1399#issue-886294818


When I build h5p-rest-example-client and serve from h5p-rest-example-server like this:

```
server.use(
    express.static(path.join(__dirname, '../../h5p-rest-example-client/build'))
);

server.get('/', (req, res) => {
    res.sendFile(
        path.join(__dirname, '../../h5p-rest-example-client/build/index.html')
    );
});
```
The editor don't show up. But you can see content list

![](https://user-images.githubusercontent.com/22095242/117773179-a3807080-b255-11eb-88ed-9e4d859dfe8f.png)


Its working when they are on different ports (Production Mode):



![](https://user-images.githubusercontent.com/22095242/117773318-c7dc4d00-b255-11eb-9886-41845a2d2ff9.png)

image

Nodejs: v14.15.3
React: v17.0.2
OS: Windows 10

**Comment by sr258** [comment]
Thank you for reporting this. It works here for me, at least in v7. There seems to be a bug in v8, which breaks the editor in the iframe mode. I'm investigating.

**Comment by sr258** [comment]
> How do I setup the DEBUG=h5p* and LOG_LEVEL=debug on my server @sr258

In MacOS you can simply prefix this when starting the application. They are environment variables.

**Comment by spsinghats** [comment]
> Thank you for reporting this. It works here for me, at least in v7. There seems to be a bug in v8, which breaks the editor in the iframe mode. I'm investigating.

I am using 7.5.2 BTW and am able to reproduce this issue

**Comment by spsinghats** [comment]
I also tried 8.0.1 but its not working

**Comment by sr258** [comment]
I was able to reproduce this issue on my Windows machine, which still runs Node 14. On my Mac with Node 15, I didn't run into this error... I'm still trying to figure out what's going on here.

**Comment by sr258** [comment]
This possibly might be the same issue as described here: https://stackoverflow.com/questions/63610932/express-static-network-requests-stuck-on-pending

If it's possible for you, you might want to try an upgrade to Node 15. If you need to stick to an LTS release, an upgrade to Node 16 might help. (It's not in LTS status yet, though, but an active release at the moment. It will become the next LTS version, though)...

I've upgraded my Windows machine to Node 16 an the issue disappeared.

**Comment by sr258** [comment]
@spsinghats @Progressive-Programmer Does updating NodeJS help?

**Comment by Progressive-Programmer** [comment]
@sr258  yeah, it worked fine with Node 15. Thanks !!

**Comment by sr258** [comment]
Great! Closing the issue.
