### ISSUE TITLE
Production build of h5p-rest-example-client is not working

### ISSUE THREAD

**Issue by spsinghats** [Lumieducation/H5P-Nodejs-library#1399]
When I build **h5p-rest-example-client** and serve from **h5p-rest-example-server** like this:
```index.ts
server.use(
    express.static(path.join(__dirname, '../../h5p-rest-example-client/build'))
);

server.get('/', (req, res) => {
    res.sendFile(
        path.join(__dirname, '../../h5p-rest-example-client/build/index.html')
    );
});
```

The editor don't show up. But you can see content list

![image](https://user-images.githubusercontent.com/22095242/117773179-a3807080-b255-11eb-88ed-9e4d859dfe8f.png)

Its working when they are on different ports (Production Mode):

![image](https://user-images.githubusercontent.com/22095242/117773318-c7dc4d00-b255-11eb-9886-41845a2d2ff9.png)

Nodejs: v14.15.3
React: v17.0.2
OS: Windows 10

**Comment by sr258** [comment]
Resolved by updating to Node 15. See https://github.com/Lumieducation/H5P-Nodejs-library/issues/1398#issuecomment-839488436
