### ISSUE TITLE
Display Editor

### ISSUE THREAD

**Issue by TheoGdrt** [Lumieducation/H5P-Nodejs-library#15]
Hey, I'm a young developer but I do my best to fully understand the code and to propel the project. I was wondering if you managed to display the editor, even if there're lots of bugs. I tried to import every missing file, then to display the .h5p-editor class but I think this is not a good practice (and it didn't work). Thanks a lot !

**Comment by JPSchellenberg** [comment]
Hey,
we are happy that you want to help us. We managed to display the editor (without functionality right now). You have to clone the project and run `npm install` and `npm start`, then you should see the editor in a browser on `http://localhost:8080`.
We are basically doing the same. From what you wrote, I assume you might be missing the H5PIntegration Object.
You can see how the H5PIntegration.editor object is built [here](https://github.com/Lumieducation/H5P-Editor-Nodejs-library/blob/master/src/index.js#L122) and the default integration [here](https://github.com/Lumieducation/H5P-Editor-Nodejs-library/blob/master/src/default_editor_integration.json).

Another important aspect is how the editor is initialized. We copied the script from the [wordpress-plugin](https://github.com/Lumieducation/H5P-Editor-Nodejs-library/blob/master/src/client/h5p-editor.js). 

If you have any further questions, I am happy to help. If you want me to have a look at your code, just use [gist](https://gist.github.com).

Best,
JP

**Comment by TheoGdrt** [comment]
Thank you very much, I take a look and I'll keep you informed !
Théo

**Comment by TheoGdrt** [comment]
So I cloned the project and ran `npm install` with a few warnings:
![image](https://user-images.githubusercontent.com/44611146/58878357-61e30480-86d3-11e9-9036-059745247462.png)

Then I made a `npm start`. The server launched with many errors in the Chrome console : lots of files were missing.
![image](https://user-images.githubusercontent.com/44611146/58879233-7de7a580-86d5-11e9-81fc-dcc0ac857b19.png)

So I downloaded and placed theses files (from the H5P project) where they were necessary:
![image](https://user-images.githubusercontent.com/44611146/58878511-bbe3ca00-86d3-11e9-8d2d-0593451390c2.png)

At this point : In my web browser I only can see a single "Create" button (no Editor):
![image](https://user-images.githubusercontent.com/44611146/58878726-33195e00-86d4-11e9-81a8-05365b637deb.png)

To make a test, I placed some `console.log` in the .js librairies to see if they are correctly implemented by the server, and this is OK. It seems that the Editor is implemented but is not displayed. But from what you wrote, I should be able to see the Editor in my web browser at this point.

Thank you, I will try to help you on this very interesting project !

**Comment by JPSchellenberg** [comment]
Did you copy the files from `src/client` into `h5p/editor/wp`? It looks like they are missing and the `postinstall`-script from [package.json](https://github.com/Lumieducation/H5P-Editor-Nodejs-library/blob/master/package.json#L10) did not copy it.

**Comment by TheoGdrt** [comment]
Thank you, it's working :)
Now I'm going to look at the issues to try to understand and to work on them.

**Comment by JPSchellenberg** [comment]
Great! I opened a new issue (#18 ) for your failing install-process and I will close this issue.
