### ISSUE TITLE
Add Debug Logger 

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/H5P-Nodejs-library#153]
Hey,

I am badly missing a debugging logger like [debug](https://www.npmjs.com/package/debug). Sometimes I get questions in Slack from people that want to integrate the library but fail to do so and without an error/info log it is really hard to see why it fails. We talked in #83 about a logger like winston, but that was more a solution to report errors back to people who are using the Editor via the web interface - as far as I understood it.

I am talking about a logger for developers that are implementing the library.

I would opt for [debug](https://www.npmjs.com/package/debug) as I am used to it and it is also used by a lot of packages like express.

@sr258 Do you have any other suggestions or comments?

**Comment by sr258** [comment]
I'm fine with using the debug package for this purpose. We should have some config value that enables and disables debugging and discard debugging messages if the server is in production mode.

**Comment by JPSchellenberg** [comment]
The configuration of debug is done via environment variables: https://www.npmjs.com/package/debug#environment-variables

The thing I am thinking about is whether we want to use winston for the reporting back in the web interface. It wouldn't make sense to have two debugging loggers. But I have no experience with winston and how to handle the reporting.
