### ISSUE TITLE
Separate implementations from (core)-Editor

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/H5P-Nodejs-library#154]
After thinking about the code for a bit I noticed that some of our files in `src/` are basically implementations:
- FileContentStorage.ts
- EditorConfig.ts
- FileLibraryStorage.ts
- InMemoryStorage.ts
- JsonStorage.ts
- User.ts

I think we should keep them in the Repo as examples and some kind of default implementations, but separate them from the source-code in `src/` as it makes it clearer how to implement the library.

@sr258 What do you think?

**Comment by sr258** [comment]
Yes, I'm fine with moving them to some "implementation" folder or something like this. We should definitely keep them at hand, though, as they are needed by many tests.
