### ISSUE TITLE
H5P edit Play and other API calls response error in build but not in development 

### ISSUE THREAD

**Issue by Progressive-Programmer** [Lumieducation/H5P-Nodejs-library#1542]
It's a Reactjs project and we integrated H5p-Nodejs-library into our app. 
The h5p components run fine in local but on server the calls are not responding. 
we earlier had this issue where one of the json file api call remained pending.
Please let us know what other details will be required
![Screenshot 2021-07-01 at 9 49 23 PM](https://user-images.githubusercontent.com/25490780/124157603-92661a00-dab6-11eb-9532-7b5d48067346.png)

**Comment by sr258** [comment]
In the past a similar error was connected to NodeJS versions. Upgrading to Node 16 helped. If you aren't on 16 yet, you should try upgrading.

**Comment by sr258** [comment]
Do you also get a 304 response code in development? It looks like there's a cache on the server for this route.

**Comment by Progressive-Programmer** [comment]
https://github.com/Lumieducation/H5P-Nodejs-library/issues/1542#issuecomment-872414030

Should we upgrade to Node 16 both on frontend and backend?

**Comment by Progressive-Programmer** [comment]
https://github.com/Lumieducation/H5P-Nodejs-library/issues/1542#issuecomment-872416835

Yes we do get 304 response
In the image 304 response is there in edit API

**Comment by sr258** [comment]
If your fronted proxies the backend, both. Otherwise only the backend might be enough. Is there any other reverse proxy (nginx or some ingress controller) in your production setup?

Is the screenshot from dev or production?

**Comment by Progressive-Programmer** [comment]
https://github.com/Lumieducation/H5P-Nodejs-library/issues/1542#issuecomment-872425268

The screenshot is from production. 
I need to ask and confirm if there's any reverse proxy. Allow me some time.

**Comment by sr258** [comment]
Take all the time you need. It would also be important to know if you get any console errors in the browser.

**Comment by Progressive-Programmer** [comment]
https://github.com/Lumieducation/H5P-Nodejs-library/issues/1542#issuecomment-872449463

No there's no reverse proxy. And there is no error in console as well 

Console
<img width="1440" alt="Screenshot 2021-07-02 at 3 24 27 PM" src="https://user-images.githubusercontent.com/25490780/124257374-ef5ee000-db49-11eb-887d-99291af89589.png">

304 response 
<img width="1440" alt="Screenshot 2021-07-02 at 3 24 20 PM" src="https://user-images.githubusercontent.com/25490780/124257347-e79f3b80-db49-11eb-9684-c783e83648fc.png">

**Comment by sr258** [comment]
Do you get the 304 response in **development**, too?

**Comment by Progressive-Programmer** [comment]
https://github.com/Lumieducation/H5P-Nodejs-library/issues/1542#issuecomment-872876797

not, this issue has not come in development so far

**Comment by sr258** [comment]
But do you see the same 304 response or do you get a 200 response there?

**Comment by Progressive-Programmer** [comment]
> But do you see the same 304 response or do you get a 200 response there?
The response is 304 in development as well.

**Comment by Progressive-Programmer** [comment]
DEvelopment edit api response 
304 

![Screenshot 2021-07-02 at 3 56 17 PM](https://user-images.githubusercontent.com/25490780/124261262-34851100-db4e-11eb-898f-dedefc99117d.png)

**Comment by Progressive-Programmer** [comment]
> But do you see the same 304 response or do you get a 200 response there?

Hi, can you please respond further so we can rectify the issue.

**Comment by sr258** [comment]
Have you upgraded to a newer Node version yet?

**Comment by Progressive-Programmer** [comment]
> Have you upgraded to a newer Node version yet?

The backend is upgraded to Node 16

**Comment by sr258** [comment]
The next steps would be the usual debugging procedure:

- Compare the response payload in development and production: are they different? If the JSON structure is fine in production it means something's wrong on the client; if the JSON structure is incorrect, something is wrong on the server
- Add breakpoints in the client at the code line at which you make the request to the server; is the data you pass to loadContentCallback the same as in production?

Check that you'e included all .json in the h5p-server package in your production files. There are the files like "playerAssetList.json" that must be present, otherwise the player doesn't know which files must be loaded.

Without knowing what you're doing exactly, I can't help you more than give you these general debugging tips. The code is yours after all and you know best how your system differs between your production and development setup.

**Comment by sr258** [comment]
@Progressive-Programmer Were you able to fix this?
