### ISSUE TITLE
Remove / update outdated documentation

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#166]
The README documentation is from a much earlier state of the project. It must be updated or (I would prefer this) reduced to avoid redundancies. The interfaces don't have to be repeated in the readme. Instead a references to the types.ts lines should suffice. Maybe we should add JsDoc comments to the interfaces. (Need to pull this up from the implementations)

**Comment by JPSchellenberg** [comment]
Closing this as #180 duplicate.
