### ISSUE TITLE
h5p-react: How to test Component using an H5P Component?

### ISSUE THREAD

**Issue by newlukai** [Lumieducation/h5p-nodejs-library#1829]
I've a React app, created with and still using create-react-app.

For this app I wrote a (functional) Component which renders an `H5PPlayerUI` Component.

Turns out, this works.

Now I try to write a simple Jest testcase for this Component like:

```
import React from 'react';
import {shallow} from "enzyme";
import {Preview} from "./Preview";
import {Provider} from "react-redux";
import {injectStore} from "../../../../api/util";
import {store} from "../../../../redux/store";
injectStore(store);

test("renders Preview", () => {
  shallow(<Provider store={store}><Preview onCloseClick={() => {}}/></Provider>);
})
```

Running the tests (`npm run test`) leads to an error:

```
TypeError: Cannot read property 'Component' of undefined

       6 | import { useIntl } from "react-intl";
    >  7 | import {H5PPlayerUI} from "@lumieducation/h5p-react";
         | ^
       8 | import {H5PApi} from "../../../../api/h5pApi";
       9 |

      at node_modules/@lumieducation/h5p-react/src/H5PPlayerUI.tsx:26:48
      at node_modules/@lumieducation/h5p-react/build/umd/H5PPlayerUI.js:3:17
      at Object.<anonymous> (node_modules/@lumieducation/h5p-react/build/umd/H5PPlayerUI.js:9:3)
      at node_modules/@lumieducation/h5p-react/src/index.ts:1:1
      at node_modules/@lumieducation/h5p-react/build/umd/index.js:3:17
      at Object.<anonymous> (node_modules/@lumieducation/h5p-react/build/umd/index.js:9:3)
      at Object.<anonymous> (src/views/Preview/Preview.tsx:7:1)
```

I added a breakpoint to the `H5PPlayerUI.js` file right after `require("react")` and inspected the return value of the `require` call. It's the React module but without a `default` property/export.

Unfortunately, I'm not that deep in all the module systems and the build and run processes of React, Jest and your library.

I'm wondering if there's a way to let the tests pass.

**Comment by sr258** [comment]
What module system do you use in jest and in the application? If you use native ES modules in jest, this might be the cause, as our component is compiled for es2015 and umd.

**Comment by newlukai** [comment]
Good question. And I need to confess I'm a bit lost here.

The tsconfig.json has set the `module` to `esnext` in its `compilerOptions`.

The generate-react-cli.json doesn't specify anything about the module system.

The Jest configuration also does not make any setting regarding the module system. And reading [the corresponding documentation](https://jestjs.io/docs/configuration) I'm wondering which one would be the correct one to adjust the module system.

What I can tell you is that I'm using `import`/`export` and thus would claim that I'm using ES modules.

**Comment by newlukai** [comment]
I tried to set the module system in the tsconfig.json to `es2015`. When starting the tests this automatically gets reset to `esnext` by `react-scripts` so I'm quite confident that the module system throughout the test is `esnext`.

So yes, this would be the cause for the reported issue.

Having a look in your codebase it seems that it should be a simple task to add a `esnext` version to the package. I'm going to try this.

UPDATE: Okay, so far, so wrong. Indeed it's a simple task to actually add an `esnext` build. But how to decide which build is to be used in a certain scenario by the user of the library? :facepalm: 

But having all three builds in my App, I edited the `package.json` of the h5p-react module before each test run.
- Using the UMD version I get the error described above ("TypeError: Cannot read property 'Component' of undefined").
- Using the `es2015` version or the `esnext` version both result in the same error:
   ```
    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/git/wonderful-app/node_modules/@lumieducation/h5p-react/build/esnext/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import H5PPlayerUI from './H5PPlayerUI';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import React, {FunctionComponent, RefObject} from 'react';
    > 2 | import {H5PEditorUI} from '@lumieducation/h5p-react';
        | ^
      3 | import {H5PApi} from '../../../api/h5pApi';
      4 | import {Button, ButtonType} from '../../controls';
      5 | import styles from './H5PFormatEditor.module.scss';

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (src/components/building-blocks/H5PFormatEditor/H5PFormatEditor.tsx:2:1)
   ```

**Comment by sr258** [comment]
Sorry about the delay in answering. Can you add this property to package.json that that package consumers pick up the correct module?

```
{ 
    "main": "./build/umd/index.js", // old
    "module": "./build/es2015/index.js", // old
    "types": "./build/es2015/index.d.ts", // old
    "esnext": "./build/esnext/index.js" // new

```
(See https://2ality.com/2017/06/pkg-esnext.html#package-authors)

Can you provide a minimal example with which I can try this out?

**Comment by newlukai** [comment]
Thanks for the hint regarding the esnext key in package.json. I wasn't aware of this possibility.

I just tried to build a simple example and this shows the same error:

```shell
$ cd /tmp
/tmp$ npx create-react-app h5p-react-test --template typescript
/tmp$ cd h5p-react-test
/tmp/h5p-react-test$ npm i @lumieducation/h5p-react
/tmp/h5p-react-test$ code .
```
In VS Code (or the editor of your choice), replace the content of App.tsx with this:

```tsx
import React, { RefObject } from 'react';
import logo from './logo.svg';
import './App.css';
import { H5PEditorUI } from '@lumieducation/h5p-react';

const h5pEditor: RefObject<H5PEditorUI> = React.createRef();

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.tsx</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>

      <H5PEditorUI
        contentId={"new"}
        loadContentCallback={() => Promise.resolve()}
        saveContentCallback={() => Promise.resolve({contentId: "new", metadata: {}})}
        ref={h5pEditor}
      ></H5PEditorUI>
    </div>
  );
}

export default App;

```

Back on the shell run `npm test`. This should give you the very same error I reported.

**Comment by sr258** [comment]
It took me some time to figure this out. It turns out it was not the ES module after all (Jest uses the UMD module). The problem was the way the H5PEditorUI component imported React. It used

```ts
import React from 'react';
```

instead of

```ts
import * as React from 'react';
```

It looks like the "allowSyntheticDefaultImports" in tsconfig.json makes TS work with the first one, but this option doesn't affect jest, so it breaks. I've created a PR that changes the imports: #1868 Once it's merged and released, things should work with the new version.

Note: When testing I've encountered an issue with ResizeObserver which is used in the component but not present in Jest. Here's how I've mocked it:

```ts
import React from 'react';
import { render, screen } from '@testing-library/react';
import App from './App';

class ResizeObserver {
    observe() {
        // do nothing
    }
    unobserve() {
        // do nothing
    }
}

window.ResizeObserver = ResizeObserver as any;

test('renders learn react link', () => {
    render(<App />);
    const linkElement = screen.getByText(/learn react/i);
    expect(linkElement).toBeInTheDocument();
});
```
