### ISSUE TITLE
[MongoS3ContentStorage]: always throws mongo-s3-content-storage:mongo-replace-error

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/h5p-nodejs-library#1864]
The MongoS3ContentStorage uses a [updateWriteOpResult](https://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#~updateWriteOpResult) named `replaceResult` and looks for the `acknowledged` property:

The `acknowledged` property does not exist on a `updateWriteOpResult` object. See [updateWriteOpResult](https://mongodb.github.io/node-mongodb-native/3.6/api/Collection.html#~updateWriteOpResult). 
So the code will always throw the `mongo-s3-content-storage:mongo-replace-error`.

Code: https://github.com/Lumieducation/H5P-Nodejs-library/blob/c6e955d281d001ec4499fcd6e83d887b84fcad81/packages/h5p-mongos3/src/MongoS3ContentStorage.ts#L162

I think we should check for the `replaceResult.result.ok` property, which is set to 1 if the command executed correctly.

**Comment by sr258** [comment]
Might be a mistake when I updated the mongodb version.

**Comment by JPSchellenberg** [comment]
Yeah, it looks like MongoDB was updated but this was not seen. What's strange is that typescript did not throw an error. My vscode shows me that this property does not exist:

<img width="629" alt="Screenshot 2021-11-04 at 19 36 34" src="https://user-images.githubusercontent.com/9697985/140399709-3172950c-3dfd-4d16-aaf4-a07fe3b6fb09.png">

I will fix it tomorrow.

**Comment by JPSchellenberg** [comment]
My bad. The new MongoDB 4.x driver has the acknowledged property: https://mongodb.github.io/node-mongodb-native/4.1/interfaces/UpdateResult.html

The problem was / is, that the injected mongodb-client was 3.x. So if you don't construct the mongodb-client via the provided `dbImplementations.initMongo()` you end up with this problem..
