### ISSUE TITLE
wp/h5p-editor.js missing

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#188]
We still reference the file /editor/wp/h5p-editor.js in our code (H5PEditor.js:406) but it is not included in the repository anymore. We either have to re-add it (not sure what it did) or remove the reference.

**Comment by JPSchellenberg** [comment]
`/editor/wp/h5p-editor.js` was the client-side implementation of the editor. It initialized the editor via `new ns.Editor(undefined, undefined, $editor[0]);` which is now done in the [default renderer](https://github.com/Lumieducation/H5P-Nodejs-library/blob/master/src/renderers/default.ts#L71). I will remove this from the code.
