### ISSUE TITLE
Build pipeline stage install useless

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#192]
Currently, the build pipeline stage 'install' is not useful as ``npm install`` also executes a build. Thus 'install' and 'build' are identical.

**Comment by JPSchellenberg** [comment]
You are right. `npm install` is also called in every test-stage. I added it nonetheless to have a better feedback at which stage the tests fail. I could remove the `install`-stage, but if the `install` fails, it would show in the `build`-stage and it would look like the `build`-stage failed. Should I remove it or keep it?

**Comment by sr258** [comment]
I think there are two solutions:

1. Keep the scripts as they are and remove the 'build' stage and rename install to 'install+build'. Then it's clear where the error lies.
2. Don't call build after install. That way the stages are clean. It would mean that newcomers who don't know about TypeScript are confused that the project doesn't work.
