### ISSUE TITLE
externalDispatcher issue

### ISSUE THREAD

**Issue by jathevan** [Lumieducation/h5p-nodejs-library#1977]
<img width="860" alt="Screenshot 2021-12-13 at 11 15 48" src="https://user-images.githubusercontent.com/17761069/145792374-0ecf8f1a-a164-4bbc-9ffd-7c3cdd00708f.png">

@sr258

**Comment by jathevan** [comment]
![image](https://user-images.githubusercontent.com/17761069/145798572-bcbd4117-9f26-4157-98d8-f2f5f3c90a1a.png)

**Comment by sr258** [comment]
@jathevan Has this been resolved by 9.0.7?
