### ISSUE TITLE
How to run example

### ISSUE THREAD

**Issue by rcarcasses** [Lumieducation/H5P-Nodejs-library#199]
**Is your feature request related to a problem? Please describe.**

I would like to run the examples provided

**Describe the solution you'd like**

Some instructions in the README.md about how to run the test would be great.
Additionally, something like `yarn example` would be amazing.

**Describe alternatives you've considered**

`node example/express.js`, doesn't seems to work.

**Comment by sr258** [comment]
You can run the example this way:
(You need Node >10.16 and NPM)

1. Clone the repository
2. ```npm install```
3. ```npm run build```
4. ```npm start```

You can then open the URL http://localhost:8080 in any browser.

**Comment by rcarcasses** [comment]
Awesome! Thanks @sr258!
