### ISSUE TITLE
build folder missing in @lumieducation/h5p-redis-lock@9.0.6

### ISSUE THREAD

**Issue by cabauman** [Lumieducation/h5p-nodejs-library#1997]
Hello! Version 9.0.6 of h5p-redis-lock seems to be missing the build folder upon installation. Version 9.0.5 is fine though.

**Comment by cabauman-kidsloop** [comment]
Are you closing this because you're unable to reproduce? I checked the latest npm package 9.0.10 and the files still aren't there. I'm trying to compare the diff between 9.0.5 and 9.0.6 but not seeing anything that sticks out so far.

**Comment by cabauman-kidsloop** [comment]
Hi @sr258.
Are you closing this because you're unable to reproduce? I checked the latest npm package 9.0.10 and the files still aren't there. I'm trying to compare the diff between 9.0.5 and 9.0.6 but not seeing anything that sticks out so far.

**Comment by cabauman** [comment]
Hi @sr258.
Are you closing this because you're unable to reproduce? I checked the latest npm package 9.0.10 and the files still aren't there. I'm trying to compare the diff between 9.0.5 and 9.0.6 but not seeing anything that sticks out so far. If I can find out what's wrong I'd be happy to make a PR.

**Comment by sr258** [comment]
Oh, sorry I thought this was just a glitch when building the 9.0.6. I'll reopen.

**Comment by cabauman** [comment]
No problem at all. I'm just using 9.0.5 for the time being.

**Comment by sr258** [comment]
It looks like this was caused by a missing workspace directory in the CI configuration. Hopefully, the next version will include code again. As there were no changes to the lock, I won't trigger a release just for this, though.,

**Comment by cabauman** [comment]
Thanks for the update! I'll keep an eye out for the next release then.

**Comment by sr258** [comment]
@cabauman Fixed in 9.2.0.

**Comment by cabauman** [comment]
Confirmed!
