### ISSUE TITLE
I am very interested

### ISSUE THREAD

**Issue by TheoGdrt** [Lumieducation/H5P-Nodejs-library#2]
I am very interested in this project too !

**Comment by JPSchellenberg** [comment]
Hey,

yes, I have done some research and managed to get the Editor running with a few bugs. Tomorrow, I will push my work and you can have a look at it. I will also publish some kind of documentation about how the H5P-editor works. (See issue #1 )

Best
JP

**Comment by TheoGdrt** [comment]
Hello,

This is great news ! Thanks !

Best
Théo
