### ISSUE TITLE
Check if library id is really need

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#203]
Currently, we assign library ids to newly installed libraries and these can be retrieved later on. I don't think we really need those. The PHP implementation had library ids, as the library metadata is stored in a relational database there and thus there naturally is a primary key (int). We must check nevertheless, if the id can be removed for our purposes, or if it is required by the client.

IInstalledLibrary currently includes this id twice (id and libraryId). We should check if this is necessary.

**Comment by JPSchellenberg** [comment]
Do you know how these ids are assigned? Are they random numbers? I think it would make more sense to use something like [string-hash](https://www.npmjs.com/package/string-hash) on the machineName, majorVersion and minorVersion to generate an integer. But we could leave that to the integration and use the machineName, majorVersion and minorVersion as identifier.

**Comment by sr258** [comment]
I think the PHP implementation uses the database unique primary key for this. Assigning them by hashing the "ubername" will be fine. My hopes are that we can get rid of them anyway, as we don't use them at all. We must check, whether the client expects them, though.
