### ISSUE TITLE
Proposal: Use temporary storage for files added to existing content

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#214]
I think it would be a good idea to use the temporary storage mechanism that has been added recently not just for files that are added to unsaved content, but also for files that are added to already existing content. The reason is that adding files directly to the content folder of already existing content is a problem when the author has decided not to save the content after all. We'd have to make sure that the files that were already added to the piece of content are removed after a timeout. This leads to several problems:

1. If someone downloads the piece of content in that period, we would currently include these (invalid and unnecessary) files (as we just include all files in the content folder).
2. We'd have to implement the same temporary file expiration mechanism twice (once for the temporary storage, once for the content folder).
3. If the system misses temporary files in a content folder (crash, bug, whatever), these files might exist in the content folder forever. (This actually happens in the H5P PHP implementation from time to time).

Even though the PHP implementation does not use temporary storage for this purpose, I think we should. That way the content in content storage would always only include the files that are really needed!

It would work like this:

1. Author adds file in client --> servers adds it to temporary storage --> path of file returned to client is suffixed with #tmp
2. Client requests file from server --> server (ContentManager) checks if file is in content storage --> if not, check in temporary storage --> serve image 
3. When author presses "save" --> server copies files from temporary storage to content storage and deletes temporary files 

The difference to the mechanism at work when dealing with unsaved content differs only in number 2, where the server has to check in temporary storage if a file doesn't exist in the regular storage. This could be implemented in ContentManager and be transparent to the implementation. (The whole feature would be transparent to the implementation in general).

@JPSchellenberg What do you think?

**Comment by JPSchellenberg** [comment]
That sounds good. When is the content.json on the server updated? Only when the user hits `save`, or am I wrong? So if the user uploads a file it would go into the temporary storage and only the client-version of the content.json is updated, right? Then we would have to remove the `#tmp` tag when the user hits `save`. 
If it works that way, I think this is a very good solution.

**Comment by sr258** [comment]
Yes, it works like you think it does. The only worries I have is that some custom editor widgets might store a reference to a file in content.json in a way that we don't understand/know about and that we miss copying it then. (IFrameEmbed seems to be a candidate for this). 

I'm currently working on parsing the content.json files for file references and it works fine with most of the hub examples.

**Comment by JPSchellenberg** [comment]
That is something hard to anticipate. I think we should go this way and see if we encounter widgets that do these things.
