### ISSUE TITLE
Proposal: separate "in the wild" tests and static functionality test

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#216]
Currently, our tests called by npm run test are a mixture of two types of tests:

1. tests that use mock-up data we have in our repository
2. tests that use test data that is downloaded from the H5P Hub

It might be a good idea to separate those two types into different directories and npm scripts, as the tests in number 2 will be more fragile. A failure here can happen at any time, when the H5P core changes and we haven't updated accordingly. (Of course, they are also useful to test whether features work with real content.)

Tests of category 1 however will be more stable and will be more useful as regression tests. 

My proposal is to have a special directory for "in the wild tests" (category 2) that is still called by the CI pipeline. At the same time, we try to remove dependencies of tests of category 1 on dynamically downloaded H5P packages and put them into the repository. 

What do you think, @JPSchellenberg?

**Comment by JPSchellenberg** [comment]
I would agree. For me, your category 1 tests are unit-tests and category 2 are integration-tests. I also noticed that the `PackageExporter`-tests take around 30s, which is a really long time if it is run with `npm run test:watch`. So, I think we should try to have unit-tests that only depend on the code we have written, everything else should be mocked. Unfortunately, I am no expert in these things, but I will have a look at how we could mock everything. 
So yes, I agree with you - we should separate these tests.

**Comment by sr258** [comment]
I think the unit tests can have dependencies on .h5p packages - we should just copy them into the repository. Several things simply can't be tested without having real h5p packages to test against.
