### ISSUE TITLE
Upgrade H5P core to 1.24

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#217]
Joubel has release core API 1.24 today. All the Hub files now require the core API version and our tests fail because of this.

**Comment by JPSchellenberg** [comment]
Very good job keeping an eye on that. I would have missed the release..

**Comment by sr258** [comment]
We can use https://github.com/Lumieducation/H5P-Nodejs-library/tree/try/update-1.23.1 as a basis. This will block all further merges, as our CI tests fail.

**Comment by JPSchellenberg** [comment]
I just started https://github.com/Lumieducation/H5P-Nodejs-library/tree/update/h5p-core-1.24, but we could also merge master back into update-1.23.1 and start from there. What would you prefer?

**Comment by sr258** [comment]
I think working on your branch is better. Just copy over the few changes that are missing from yours.
