### ISSUE TITLE
Determine Dependencies when creating H5P-Content

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/h5p-nodejs-library#23]
At the moment the preloadedDependencies-Field of the h5p.json is taken from the preloadedDependencies-Field of the [mainLibrary](https://github.com/Lumieducation/h5p-nodejs-library/blob/editor/src/router.ts#L1340). I dont think that this is the correct way to determine the dependencies. 

The Multiple-Choice Type for example misses the H5P.ConfirmationDialog:

<img width="679" alt="screenshot 2019-01-27 at 02 50 52" src="https://user-images.githubusercontent.com/9697985/51795067-70c62180-21de-11e9-922b-d3439531bf86.png">

**Comment by sr258** [comment]
This one is built in and not a dynamic dependency.

**Comment by JPSchellenberg** [comment]
You are right. Thank you for the hint.
