### ISSUE TITLE
Documentation misses topics

### ISSUE THREAD

**Issue by jankapunkt** [Lumieducation/h5p-nodejs-library#2341]
I just found that the documentation @ https://docs.lumi.education is missing a few topics in `docs/advanced` and https://docs.lumi.education/development/status is outdated (I think).

**Comment by sr258** [comment]
What topics would help you in the docs? The status is still correct as far as the release packages is concerned.

**Comment by jankapunkt** [comment]
hey @sr258 I just realized that this only concerns the not-yet published user-state so from that point of view they are correct.
