### ISSUE TITLE
ContentTypeCache.get() throws cryptic error when cache can not be loaded

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/H5P-Nodejs-library#235]
**Describe the bug**
When `ContentTypeCache.get()` is called via `H5PEditor.installLibrary()` and the cache is not saved before, it throws the error `TypeError: Cannot read property 'filter' of undefined`.

**Environment (please complete the following information):**
 - OS: all
 - Nodejs-Version 10.16.3

**Expected behavior**
If no contentTypeCache can be loaded from the store (keyValueStore) it should throw an error like `Error: no contentTypeCache found. Please initialize contentTypeCache before calling .installLibrary`

**Comment by sr258** [comment]
resolved in #265
