### ISSUE TITLE
Ajax request failed

### ISSUE THREAD

**Issue by TheoGdrt** [Lumieducation/H5P-Nodejs-library#24]
Hello,

I'm working on the project and I'm looking at the WP and Moodle modules to understand the operation of the Server-link / AJAX requests. Did you work on that ? Did you succeed ?

Best,
Théo

**Comment by TheoGdrt** [comment]
I chose the **Multiple Choise** as an example.
I placed the necessary **semantics.json** (found on Github : https://github.com/h5p/h5p-simple-multiple-choice/blob/master/semantics.json ) file to the right path : h5p/libraries/H5P.MultiChoice-1.13
This allowed me to **display the Multiple Choice** module on screen 👍 
![image](https://user-images.githubusercontent.com/44611146/59603204-171cb000-9109-11e9-8ebc-29d7cd204696.png)

I can fill in the inputs, then when I click on the Create button, the console tells me that the POST route is not existing. In the express.js file, I created a virtual POST route to simulate it : 
`server.post('/', function(req, res) {
    //fake post here
});
`

It virtually solved this console issue.
But now I got a new one 👎 
![image](https://user-images.githubusercontent.com/44611146/59603579-0de01300-910a-11e9-8b21-90b216df7426.png)

Because of : [h5peditor-editor.js:276]
![image](https://user-images.githubusercontent.com/44611146/59603882-d7ef5e80-910a-11e9-9964-6e258e47b863.png)

I don't understand why this is not working with this function.
Sorry if I have a very basic level understanding of the problems...

**Comment by sr258** [comment]
I suppose just you have to implement the behavior of the POST action in the server and return some kind of data?

**Comment by JPSchellenberg** [comment]
The create button is not implemented yet. @sr258 is right - but as far as I know, the server has to redirect the request if it is successful.
