### ISSUE TITLE
Export interfaces

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/H5P-Nodejs-library#257]
Hey,

I think the interfaces that have to be implemented by the user should be exported from our module so that you can use 
```
import { IEditorConfig } from 'h5p-nodejs-library';
```
Unfortunately, I could not figure out how to do this properly.
@sr258 any ideas?

**Comment by jankapunkt** [comment]
Would this strictly require typescript for my implementation?

**Comment by JPSchellenberg** [comment]
No. We will always release for plain javascript. Exporting interfaces just enables typescript users to have type checking.

**Comment by sr258** [comment]
https://cameronnokes.com/blog/the-30-second-guide-to-publishing-a-typescript-package-to-npm/ seems like a decent guide. I‘ll do this tomorrow.
