### ISSUE TITLE
Documentation on how to access the log

### ISSUE THREAD

**Issue by jankapunkt** [Lumieducation/H5P-Nodejs-library#260]
**Is your feature request related to a problem? Please describe.**
I run into some errors and I would like to get access to the log, since some lines before there is a `log.verbose` statement. Could you please update the documentation on how to use the log or how to pass a Logger implementation?

**Describe the solution you'd like**
Some short code snippet on how to use / pass the logger in an implementation. 

**Describe alternatives you've considered**
I am not sure about that

**Comment by JPSchellenberg** [comment]
I will add this to the documentation. You need to pass a environment variable called ‚DEBUG‘. See [debug docs](https://www.npmjs.com/package/debug).

To log all library related things you would use something like ‚DEBUG=h5p:* node script.js‘

You can also set the Loglevel via environment ‚LOG_LEVEL‘. Default is ‚info‘.

To get the verbose log use:
‚DEBUG=h5p:* LOG_LEVEL=verbose node script.js‘

**Comment by jankapunkt** [comment]
Thanks a lot, it works. I would leave the issue open, since others may benefit from this a lot when doing their implementations.
