### ISSUE TITLE
Add Linter to H5P-Nodejs-Library

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/h5p-nodejs-library#28]
Hey,
we need a linter for this project. So far I have only experience with TSLint, but since we are going to use ES6 we cannot use TSLint.
@rtens Do you have any suggestions? I found these three:
- [x] ESLint
- [ ] JSLint
- [ ] JSHint

**Comment by rtens** [comment]
Just realized that I've never used a linter since you don't miss it if your test coverage is high enough.

So how about no linter? 

Otherwise any of those will probably do.

**Comment by JPSchellenberg** [comment]
I think linters such as ESLint are more about a common code-style than testing functionality. See [airbnb-eslint-config](https://github.com/airbnb/javascript/blob/master/README.md#arrow-functions), which forces everyone who is on the project to use the same style. Right now ESLint looks good to me.

**Comment by rtens** [comment]
I see. So it would replace *prettier* as well?

**Comment by JPSchellenberg** [comment]
As far as I understand it is like this:
*prettier* is used for formatting-rules like maximum length of a line and *linters* are used for code-quality-rules like no-unused-variables or always use arrow-functions.
