### ISSUE TITLE
Cleaning up example

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#281]
I think the Express example has become quite big - I'd like to refactor it and also remove parts (e.g. copying examples from the h5p.org site - we have a working h5p hub after all). @JPSchellenberg would you agree?

**Comment by JPSchellenberg** [comment]
I totally agree. I would like to simplify it a lot. As mentioned in #284 I would like to provide 'default implementations' for a very easy getting started. In our example these implementations would be the FileStorage implemtation and an express-router.

I am imagining somethin like this four our example:
```js
import * as H5P from 'h5p-nodejs-library';
import H5PConfig from './config';
const h5p = H5P.fs(H5PConfig, 'path/to/libraries', 'path/to/content', 'path/to/tmpDir');

express.app.use('/h5p', H5P.expressRoutes(h5p));
```
