### ISSUE TITLE
Should we wrap all methods of utility classes in H5PEditor / H5PPlayer?

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#282]
So far, most functionality that must be called from the implementation can be accessed by calling methods of H5PEditor or H5PPlayer. There are several cases, however, where the implementation must call methods of properties of H5PEditor (e.g. call h5pEditor.contentManager.loadContent(...)) or even use the classes exported in index.ts (e.g. construct a new PackageExporter for exporting packages).

I'm not all that happy with this approach and I think it would be better if we have wrapper methods in H5PEditor/H5PPlayer for all calls of the implementation.

In general, I think we could refactor the H5PEditor/H5PPlayer classes to become the place where we validate and sanitize all user input (as far as possible), convert return values into the correct format and localize messages to the end user. All other (model domain) functionality could be moved to specific classes.

@JPSchellenberg What do you think?

**Comment by JPSchellenberg** [comment]
Yes, I would agree. I think it makes the implementation and testing easier. A good approach to determine what has to be publicly available is to look at our File-implementation in examples/ . I would also suggest adding some 'default implementations' like the file-system implementation.

**Comment by sr258** [comment]
I think this is the last issue that must be addressed before 1.0 can be released. I think we should also go through all exported interfaces and check them for consistency and documentation.
