### ISSUE TITLE
Add default file implementation

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/H5P-Nodejs-library#284]
**Is your feature request related to a problem? Please describe.**
I would like to have certain 'default implementations' like the file-implementation used in our example. 

**Describe the solution you'd like**
I would want to be able to import a default file-implementation like
```
import * as H5P from 'h5p-nodejs-library';
const h5p = H5P.fs(
    editorConfig: IEditorConfig,
    librariesPath: string,
    contentPath: string,
    temporaryStoragePath: string
);
```

**Describe alternatives you've considered**
We could add this to this to this library or make another repo/npm-package.

@sr258 what do you think?

**Comment by sr258** [comment]
Having default implementation is fine to me (we can move the ones in the example to the regular code). I don't like having a simple "FileImplementation", though, as I think having one for libraries and temporary files is totally fine, but not so much for content. It also obscures to the novice implementer that there are 3 different storage classes at work.
