### ISSUE TITLE
Improve Tests.

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/H5P-Nodejs-library#285]
After reading a [guide](https://medium.com/@me_37286/yoni-goldberg-javascript-nodejs-testing-best-practices-2b98924c9347) on javascript testing best practices I came to the conclusion, that we should try to improve our tests as I think they are sometimes too verbose and the real intent is not always clear at the first look.

But one thing I'd like to discuss is Number 4 from the article. (4. Stick to black-box testing: Test only public methods).

I am not sure what is exactly meant: Should we only test the public available methods of our package? So only H5PEditor and H5PPlayer methods? Or is it meant a little broader like testing all public methods of our domains/classes like we already do?

**Comment by sr258** [comment]
Having better tests is fine, but in many cases the classes we have to test aren't that simple: you need a lot dependencies for them to work, you need to prepare input variables etc. This makes tests verbose, but I don't really see a way around that. Can you give examples of how you would make tests more clear?

I haven't read the text yet, but I think #4 means that you only test public methods of classes. Otherwise you'd only have integration tests.

**Comment by sr258** [comment]
I now have read most of the text and it indeed advocates only testing public interfaces, which would be H5PEditor and H5PPlayer in our case.

I don't agree to this idea, as testing the components inside with their own unit tests was super useful while developing them! That way I didn't have to integrate them into the system before they were ready. I also don't believe that it would be easy to supplement every test we currently have and reach high code coverage if we just call everything from the highest level. While the lean examples look nice, I'm skeptical that they're that easy to achieve in real life. They also seem to presuppose lots of information about how stuff works internally (e.g. a certain function in a dependency X must be called when doing Y), which means that they aren't real blackbox tests either.

Further, we should take into consideration that the library will not grow beyond a certain point (once we've got everything the PHP implementation does and maybe a bit beyond that) and that having more tests won't lead to an unmaintainable mess in my opinion. 

And finally, many of the classes we have can be used in other use cases than just a regular editor or player. They are excellent to automate certain behaviour of H5P (e.g. auto-generate content from databases, perform mass cli-operations, offering a way of performing automated test on **h5p content**). Maybe they aren't exported at the moment, but they might be in the future and then we'd have to test them "according to the article".

**Comment by JPSchellenberg** [comment]
You are right. And as I don't see a way to improve our tests I will close this issue.
