### ISSUE TITLE
Implement reference test for H5P Viewer

### ISSUE THREAD

**Issue by rtens** [Lumieducation/H5P-Nodejs-library#31]
In order to prove that the Node.js port is equivalent with the PHP library, we need to implement it into a reference project that can quickly render several H5P packages which we can then compare with the same packages rendered by the port.

**Comment by rtens** [comment]
@JPSchellenberg looks like I don't have rights to edit assignee or labels of this task. Could you add me to the repo?

Also: would you put the PHP implementation into this repo or into its own?

**Comment by JPSchellenberg** [comment]
You are now added as an admin to the repo. I would prefer to have everything in one repository and separate them later if necessary.

**Comment by rtens** [comment]
I had an good look at the [PHP Library](https://github.com/h5p/h5p-php-library) as well as the [Wordpress Plugin](https://github.com/h5p/h5p-wordpress-plugin) and realized that we can't compare our output to the "reference" implementation (i.e. the PHP Library), since the library doesn't seem to be responsible for most of the output generation. This is handled by the plugin - [here](https://github.com/h5p/h5p-wordpress-plugin/blob/master/public/class-h5p-plugin.php#L858) and [here](https://github.com/h5p/h5p-wordpress-plugin/blob/master/admin/class-h5p-plugin-admin.php#L163).

We could try to compare our output to the Wordpress Plugin but I don't think that's worth the trouble. Instead, I would suggest that we use the [examples from H5P.org](https://h5p.org/content-types-and-applications) as the basis for a manual test suite. Along with the executable specification (#32), this should give us a high level of confidence.

So I vote to close this issue. What do you think, @JPSchellenberg ?

**Comment by JPSchellenberg** [comment]
I see. We could test against the response of their embedded versions of their examples. (For Example: `curl https://h5p.org/h5p/embed/6724`). We can either 
1. save their responses in the repository and test against them, which would make us independent from their page or
2. fetch the responses on every test, which would require that their page is online, but we would always have the latest version to test against.
Which way do you wanna go?

What aspects do you want to test?
As far as I can see we have to test 
1. the order of the scripts in the header and
2. the integration object.

**Comment by rtens** [comment]
I'll write a script that downloads examples from h5p.org and renders them so they can be verified manually. I think that's way easier and gives us a similar assurance that the rendering works.
