### ISSUE TITLE
Update/Create H5P: Move content files from tmp-dir to final destination

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/H5P-Nodejs-library#32]
At the moment all uploaded files are stored in a temporary directory. We have to move these files into their final destination when an H5P is created or updated.

**Comment by sr258** [comment]
It looks like at the moment files are directly stored in the final destination, aren't they?

**Comment by JPSchellenberg** [comment]
Yes. I implemented a quick solution to test the editor as I wanted to do some tests. To work on this we need the [tokens](https://github.com/Lumieducation/H5P-Nodejs-library/issues/46).

**Comment by rtens** [comment]
Replaced by #61
