### ISSUE TITLE
Semantic release doesn't work in package.json

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#330]
**Describe the bug**
When there is a new release, the version of the library in package.json is not updated correctly.

**Comment by JPSchellenberg** [comment]
I think this would require to make the master branch unprotected, so the release-bot can commit without a pull-request. It would also be required if we want to generate docs on every release and commit them to the repository. Do we want that?

Edit: There might be a workaround: https://github.com/semantic-release/github/issues/84 
I will try to get this running the next days.

**Comment by sr258** [comment]
@JPSchellenberg Is this fixed with the monorepo?
