### ISSUE TITLE
Negative Marking  for each wrong option

### ISSUE THREAD

**Issue by AnubhabMondal** [Lumieducation/H5P-Nodejs-library#386]
Suppose in multiple-choice Question if I want to set Marks in each option now it not possible--
   Something like for 
       correct option I set Marks=1 and for the wrong options, I set Marks= -0.5.
 so if I select the wrong options my marks will be -0.5.

If I want to achieve the features how can I proceed..? 

Can Somebody plz help me with that. @JPSchellenberg @sr258 @danielrudn 
Thanks..!!

**Comment by sr258** [comment]
If I understand you correctly, this is a general H5P question that must be adressed in the Multiple Choice Content Type of H5P itself. This library is only a re-implementation of the server component and is not concerned with individual content types. Please head over to https://h5p.org/forum/16 and ask there.

**Comment by AnubhabMondal** [comment]
Thanks @sr258
