### ISSUE TITLE
[Question] How can I get the content Id [QuestionId] ..?

### ISSUE THREAD

**Issue by AnubhabMondal** [Lumieducation/H5P-Nodejs-library#392]
Hi everyone,
 I have one question, 
Suppose I create a question from this project [Node H5p] and I want to get the **contentId**  - I need to pass that parameter to another php based application where we will maintain a mapping between H5p content id to the corresponding question id field in our application. How can we send the **contentid** from h5p to another php based application on the same server?
 Can you guys please help me with that. @sr258 @JPSchellenberg

**Comment by sr258** [comment]
When you save new content you must call H5PEditor.saveH5P(). This method returns the content ID of the newly created content and you can use it in the calling function to call an endpoint of your PHP application. 

Consider this example:

```ts
router.post('/new', async (req, res) => { // this is the NodeJS Express Router
        const contentId = await h5pEditor.saveH5P(...); // you call the h5p-nodejs-library here
        // send the contentId to an endpoint of your PHP application
}

```
I'm not sure if you can also do this without having an endpoint in your PHP application. You could also add the mapping to the database of your PHP application directly by opening a connection to the DB in NodeJS and storing the mapping through it.

But why use the NodeJS library in the first place, if you have a PHP application already? The original H5P server is in PHP and allows writing your own implementation as well. It is more complete and stable!

**Comment by AnubhabMondal** [comment]
Thanks @sr258 for valuable replay. I must try this solution.

**Comment by AnubhabMondal** [comment]
Hi @sr258 , Can you please help me on that ,
Now i used this approach and i don't understand how to send contentId to my php application.
```
router.post('/new', async (req, res) => { // this is the NodeJS Express Router
        const contentId = await h5pEditor.saveH5P(...); // you call the h5p-nodejs-library here
        // send the contentId to an endpoint of your PHP application
}
```
Here how can I send ContentId to my PHP application..?

Thanks @sr258 .

**Comment by sr258** [comment]
You can for example use the HTTP library 'Axios' for this. Install it through `npm install axios`. The library already has a dependency on it, so you don't bloat the dependencies.

You can then write something like this:

```ts
import axios from 'axios';

router.post('/new', async (req, res) => { 
        const contentId = await h5pEditor.saveH5P(...); 
        // send the contentId to an endpoint of your PHP application
        await axios.post('/your-private-http-endpoint', { questionId, contentId });
}
```
This requires your PHP application to answers to `/your-private-http-endpoint' and you must make sure that this endpoint is not reachable from outside your server (must be done in the reverse proxy).
Obviously you must also know about the questionId already, but this is something I cannot answer, as it depends on the architecture of your application.

Let me repeat: The original H5P server **IS** already written in PHP and I'd advise you to integrate it into your PHP application. I have no experience in mixing NodeJS and PHP in one application, so I can only guess how to do it. I would absolutely NOT recommend doing it and use the much more stable and mature PHP original! Even if it might be a bit daunting at the beginning, I think this is the much easier and cleaner way. Check out the WordPress, Drupal or Moodle implementation for examples.
