### ISSUE TITLE
Naming style

### ISSUE THREAD

**Issue by rtens** [Lumieducation/H5P-Nodejs-library#42]
I noticed some discrepancies regarding our naming styles. Currently, we use under_scores as well as camelCase. I vote to move consistently to camelCase since that's the dominant naming style in node.js.

What do you think, @JPSchellenberg ?

**Comment by JPSchellenberg** [comment]
I don't care if it is camelCase or snake_case as long as it is consistent. I noticed that we are not using the linter, which is meant to enforce a common coding-style. I will convert everything into camelCase and run the linter in travis, so a common coding-style is enforced.

**Comment by rtens** [comment]
Perfect, thanks
