### ISSUE TITLE
How to manage errors

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#43]
While implementing the validation of packages in h5p-extractor I've come across the problem of reporting back validation errors to the user. The way the PHP implementation does this is this:

1) [setErrorMessage(...)](https://github.com/h5p/h5p-php-library/blob/4a9ea77d470906ce1c114361493e0c94817c29d9/h5p.classes.php#L38) is called by the validation functions when a validation error occurs. This method is implemented by the plugin (e.g. Moodle or WordPress) and stores the message somewhere. It does not immediately output them
2) If there was a validation error, the messages are later pulled out again, e.g. in the function [isValidPackage()](https://github.com/h5p/h5p-editor-php-library/blob/e9261b4308cbf3c42f2e9e39b1603d0ab9ed46ef/h5peditor-ajax.class.php#L306) by calling [getMessages('error')](https://github.com/h5p/h5p-php-library/blob/4a9ea77d470906ce1c114361493e0c94817c29d9/h5p.classes.php#L54). The messages are passed on to [H5PCore::ajaxError()](https://github.com/h5p/h5p-php-library/blob/4a9ea77d470906ce1c114361493e0c94817c29d9/h5p.classes.php#L3132), which produces the response to the AJAX call (by printing out to stdout).

So far, I have opted to throw JavaScript errors when the validation produces an error, with the idea of catching these errors at a top level and then producing the corresponding response. However, the problem is that using ```throw``` and ```catch``` means that the validation process will be interrupted right away when an errors occurs. This is not the way the PHP implementation does it: it continues the validation if the error is not critical and collects all errors to report all of them to the user.

I assume you'll want the NodeJS implementation's behavior to be as close to the PHP implementation as possible. This means there must be a messaging mechanism that stores error (and info) messages and allows later retrieval of them. I've worked with generic loggers like [Winston](https://www.npmjs.com/package/winston) before, but I'm not entirely sure if they are a good fit for our purposes here. Have you had any thoughts of this yet?

**Comment by JPSchellenberg** [comment]
You are right, we want to be as close to the PHP implementation as possible. I think a valid approach could be to have each validation step as promise that resolves to an object that contains the error messages, passes the object to the next promise and to chain these promises. I would like to keep third party solutions like Winston out because I think the implementation should be as easy as possible. What do you think?

**Comment by sr258** [comment]
Using third party libraries per se doesn't mean the implementation becomes more complex, as it puts complexity into the third party. However, I still think that validation isn't the best place to use Winston. 

I've followed an approach similar to what you've suggested and am refactoring the validator now. It also becomes more readable and maintainable that way. I think I'll have a working validator by Wednesday or so.

**Comment by JPSchellenberg** [comment]
That sounds really great! :)

**Comment by sr258** [comment]
After having worked on the hub client, validation and installation, I have seen several places in which we have to report things to the user. These can be failures (Validation Error X) and success messages (Installed X libraries.) These message have to be added to the AJAX response. Reporting errors by throwing and catching a certain class of exception is fine, but how do we want to approach reporting success? Should the methods that report success return it as a string value? Or should the component that report something back call something like a messenger object?
