### ISSUE TITLE
Implement tokens

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#46]
H5P uses some kind of custom tokens that are generated by the server and passed to the server. The JavaScript client adds it to several AJAX calls of the editor (install libraries, upload libraries, files (?)). 
Token generation and checking is done in the general H5P library, so it must be implemented there, but the editor library uses the methods of it.

**Comment by rtens** [comment]
Do we use the Player library in the Editor? It doesn't appear in the `package.json`.

Since uploading and installing libraries and packages is responsibility of the Editor, I don't think the Player needs tokens to verify requests. So I'll close this issue. Please re-open if you disagree.
