### ISSUE TITLE
Dependency-order is wrong in some content-types

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/H5P-Nodejs-library#47]
When I use certain content-types (course-presentation, interactive-video, etc..) , the depedency-order seems to be wrong. It looks a lot like the error from the renderer where the depedency-order was wrong, due to the async-libraryLoader: See [here](https://github.com/Lumieducation/H5P-Nodejs-library/issues/47).

![Screenshot 2019-08-06 at 21 56 52](https://user-images.githubusercontent.com/9697985/62572954-29a7a000-b895-11e9-9728-7b7af355d22f.png)

We have two options:
1. Use an sync-libraryLoader in the editor as well.
2. Get a async-libraryLoader working. (See Lumieducation/H5P-Nodejs-library#66)

What do you think? @rtens @sr258

**Comment by rtens** [comment]
I'll integrate the async library loader from the viewer. Should solve this problem.

**Comment by rtens** [comment]
So after an inital investigation it seems that the problem is not that the libraries are loaded in the wrong oder, but tha tthe libraries of the content are not loaded at all. At least not in the [render function](https://github.com/Lumieducation/H5P-Editor-Nodejs-library/blob/master/src/index.js#L39).

@JPSchellenberg Do you agree with my conclusion or did I overlook something?

**Comment by JPSchellenberg** [comment]
@rtens I can not agree with your conclusion, as the libraries are loaded in my case:
<img width="853" alt="Screenshot 2019-08-08 at 14 55 06" src="https://user-images.githubusercontent.com/9697985/62704816-86699e80-b9ec-11e9-8b4e-c7ce64a46282.png">

Or which specific libraries do you mean?

Were the necessary libraries installed in your `/libraries`-folder?

**Comment by JPSchellenberg** [comment]
On second thought: I think the libraries are loaded from the client-side-editor-code and not determined on server-side. But then we have to figure out how and where the order is determined.

**Comment by JPSchellenberg** [comment]
I think the order is determined in the axjax call to `GET /ajax?action=libraries..`:

<img width="851" alt="Screenshot 2019-08-08 at 15 05 12" src="https://user-images.githubusercontent.com/9697985/62705583-ef054b00-b9ed-11e9-91e1-9332ed4bcf7b.png">

so we have to investigate the `getLibraryData`-method.

**Comment by rtens** [comment]
Ah thanks that's exactly the pointer I needed.
