### ISSUE TITLE
Mathematical expressions not working

### ISSUE THREAD

**Issue by dailez** [Lumieducation/H5P-Nodejs-library#471]
**Describe the bug**
Mathematical expressions as described in https://h5p.org/mathematical-expressions are not working

**Environment (please complete the following information):**
 - OS: [e.g. macOS]
 - Nodejs-Version [e.g. 22]

**To Reproduce**
1. Just add a LaTeX string to a text field (e.g. $$ some LaTeX $$) and press "done"

**Expected behavior**
The statement should be rendered in LaTeX style

**Screenshots**
![image](https://user-images.githubusercontent.com/6159851/80447608-261fe180-891a-11ea-88e3-f8af8e5cd5af.png)

This is expected:
![image](https://user-images.githubusercontent.com/6159851/80447642-40f25600-891a-11ea-8950-b1d119a351b2.png)

But this is shown:
![image](https://user-images.githubusercontent.com/6159851/80447676-62534200-891a-11ea-8d2d-83d749d42f6c.png)

**Additional context**

**Comment by sr258** [comment]
The problem with this is that H5P does not support mathematical expressions out-of-the-box. You must install an addon that adds MathJax to text fields. This has been requested by @JPSchellenberg in https://github.com/Lumieducation/Lumi/issues/410. 

Implementing this certainly is possible, but it would also require the MathJax addon to be present in every system to which the content is uploaded.

@dailez Are you using the Lumi desktop application or thinking of hosting a server with this library? If you want to run your own server the addon will work fine (once the functionality is implemented). If you use the desktop application, it will depend on the server you play out the content with.

**Comment by sr258** [comment]
Fixed in 4.0.0. You need to install the H5P.MathDisplay library to get this working in the player. For maths support in the editor, you must configure the server as explained in the documentation page on addons.
