### ISSUE TITLE
Implement GET Content-Type-Cache within Ajax-Endpoint

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/H5P-Nodejs-library#5]
The content-type-cache is a list of H5P-content-types that are installed or can be installed.

It is implemented via the [ajax-endpoint](https://github.com/Lumieducation/H5P-Editor-Nodejs-library/issues/4) with the action `content_type_cache`.
`GET /ajax?action=content_type_cache`
An example response is [here](https://github.com/Lumieducation/H5P-Editor-Nodejs-library/blob/master/src/content_type_cache.json).

Right now the content-type-cache is hard-coded.

Todo:
- [ ] Get a list of installable content-types from the H5P Hub.
- [ ] Determine local-installed content-types.
- [ ] Generate a list and serve it via [load_content_type_cache](https://github.com/Lumieducation/H5P-Editor-Nodejs-library/blob/master/src/load_content_type_cache.js)

**Comment by sr258** [comment]
I'd be willing to help out here. Do you need help or have you already started on this?

**Comment by JPSchellenberg** [comment]
That would be great! I have not started yet. You can see what is being worked on in our [project-board](https://github.com/orgs/Lumieducation/projects/9)
I will assign you this issue and move it to 'in progress'.

**Comment by sr258** [comment]
One question: What version of ECMA Script are you targeting? I personally much prefer using all the fancy 'class' syntax of the newer version instead of using functions for everything, but I think I can manage with the old style as well.

**Comment by JPSchellenberg** [comment]
I also prefer using the newer ECMA Script versions. We will use babel to transpile it down to ES5, so feel free to use classes and ES6-features. 
In fact, today, I refactored this library and replaced the function with a class [see here](https://github.com/Lumieducation/H5P-Editor-Nodejs-library/blob/master/src/index.js#L9). I merged the PR, so make sure to use the latest version with the class.
The content-type-cache-method is [here](https://github.com/Lumieducation/H5P-Editor-Nodejs-library/blob/master/src/index.js#L43).

**Comment by sr258** [comment]
Great! If you use all the new syntax, why not use TypeScript? I think it would pay off over time, as it automatically documents the code.

**Comment by JPSchellenberg** [comment]
As you can see [here](https://github.com/Lumieducation?language=typescript) I prefer TypeScript myself, but since we have a collaboration with the University of Bremen, the requirement is to use a JavaScript-Flavour, but we might use TypeScript in the future.
