### ISSUE TITLE
Library dependency not found: H5P.DragQuestionDropzone-0.1

### ISSUE THREAD

**Issue by shawnjzlee** [Lumieducation/H5P-Nodejs-library#501]
**Describe the bug**
`H5P.DragQuestionDropzone-0.1` cannot be found when using the Drag Question Content Type.

When attempting to play a created drag-question content, the error is `storage-file-implementations:get-library-metadata-not-installed`

**Environment (please complete the following information):**
 - OS: `macOS`
 - Browser: `Chrome 81.0.4044.129`
 - Nodejs-Version: `v12.10.0`, NPM-Version: `6.14.4`

**To Reproduce**
1. Create Drag and Drop Content
2. Under "Settings", add a background image
3. Under "Task", add a Drop Zone
4. Under "Task", add Text and assign to the above drop zone
5. Click "Create", error results when attempting to display the content

**Expected behavior**
Ability to see the Drag and Drop content.

**Screenshots**

![Screen Shot 2020-05-12 at 11 09 40 AM](https://user-images.githubusercontent.com/8647432/81630742-564ea080-9441-11ea-8a74-eb093d3231fb.png)

![Screen Shot 2020-05-12 at 11 09 58 AM](https://user-images.githubusercontent.com/8647432/81630748-5b135480-9441-11ea-99ba-648ec9611b0b.png)

![Screen Shot 2020-05-12 at 11 10 19 AM](https://user-images.githubusercontent.com/8647432/81630751-5d75ae80-9441-11ea-864e-85c7617c7886.png)

**Additional context**
Working on top of `master`

**Comment by sr258** [comment]
Thank you for your report!

I can reproduce the issue and will look into it.

**Comment by sr258** [comment]
I've identified the cause:
While DragQuestion references H5P.DragQuestionDropzone 0.1, it is used as a "fake library" there to enable drag & drop. So it seems the name is simply a placeholder that is is used to make drop & drop work but not present on the server (it is also not part of the h5p package downloaded from the H5P Hub when installing the content type). To fix the error, the server must probably silently ignore libraries that are referenced in content but do not exist on the server. This would be easy. However, this is speculation and I want to check how the PHP library deals with "fake libraries" before making the change in our code.
