### ISSUE TITLE
Support for mp4 360 videos

### ISSUE THREAD

**Issue by ramiouanes** [Lumieducation/H5P-Nodejs-library#502]
Hello,

First of all, great project. Thank you for this work.

I would like to know if there's support for 360 videos for interactive video content. 
I try to upload a 360 video but I get "Video format not supported." error.

Thank you in advance for the help.

**Comment by sr258** [comment]
Thank you for your bug report and kind words!

In theory MP4s should work, but for some reason uploading them at the moment doesn't work as expected. I'll have to investigate this.

**Comment by ramiouanes** [comment]
Thank you for the quick response.
That'll be great. If you can just point me to how I can run the app in debug mode, I can try to help to see why this is happening. I have very small dev skills, but as I actually need this a bit urgently I can try to increase the effort by trying to debug.

**Comment by sr258** [comment]
About enabling debug mode:

Are you using the Lumi Desktop Editor or the example NodeJS application in this repository? I'm assuming you use the Lumi Desktop Editor, but the general idea is the same.

In general you can enable the debug mode by setting these environment variables:
DEBUG=h5p*
LOG_LEVEL=debug

How you do this depends on your OS:
In Linux (and macOS I think) command line, you can prefix the environment variables to the actual program like this:
```sh
cd thedirectorylumiisinstalledinto
DEBUG=h5p* LOG_LEVEL=debug ./Lumi
```
In Windows you have to set the env. variables before you actually type in your program:
```
cd C:\Users\YOURUSERNAME\AppData\Local\Programs\lumi
set DEBUG=h5p*
set LOG_LEVEL=debug
lumi
```

**Comment by sr258** [comment]
I'm sorry, I think I read your question too quickly and misunderstood it. I thought there is a general error when uploading videos.

I'm afraid 360° videos don't currently work in the Interactive Video content type. Sorry! :( You can head over to [the H5P forum](https://h5p.org/forum) and ask whether this might be possible, but I don't think there is support for this at this moment. I've successfully added a few mp4 video that are meant to be 360, but they simply show the distorted full view.

If you have a sample video that you want to use, you could post a link, so that I can check again.

**Comment by ramiouanes** [comment]
Thank you for the response.
Based on this [forum](https://h5p.org/node/75511) and other ones, it looks like the support for 360 videos was included and the "three sixty video support" branch on "Interactive video" repository was merged with the main one.

https://github.com/h5p/h5p-interactive-video/tree/three-sixty-video-support
https://github.com/h5p/h5p-editor-interactive-video/tree/three-sixty-video-support

**Comment by sr258** [comment]
The forum post on h5p.org indicates that while this is merged, it is not enabled yet, because it is not finished. There is nothing h5p-nodejs-library can do about this, as this must be finished in the content type.
