### ISSUE TITLE
In some content-types h5p-drag-text.js throws an error

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/H5P-Nodejs-library#52]
In some content types like Course Presentation or Interactive Video the `h5p-drag-text.js` throws an error:  ![Screenshot 2019-08-09 at 17 19 32](https://user-images.githubusercontent.com/9697985/62789733-db2f1700-bac9-11e9-9bcf-60f4ec52271d.png)

**Comment by rtens** [comment]
Took me a while to find out but this is caused by an incorrect order of dependencies. DragText depends on Question so Question. Therefore, Question should be loaded first but is listed after DragText in `/ajax?action=libraries&machineName=H5P.CoursePresentation&majorVersion=1&minorVersion=20`

**Comment by JPSchellenberg** [comment]
That might be the async-libraryLoader issue.. So we still need to implement the solution from the renderer.

**Comment by rtens** [comment]
This was indeed caused by loading the dependencies in parallel. Changed it so they are loaded in serial. This problem probably also exists in the viewer. I will add a test case to confirm my hypothesis.
