### ISSUE TITLE
Use default h5p structure for content storage

### ISSUE THREAD

**Issue by benabel** [Lumieducation/H5P-Nodejs-library#532]
I'd like to preview my h5p files as standalone pages using h5p-standalone and serve the content storage generated by H5P-Nodejs-library, however I've been surprised to see that this folder do not implement the normal h5p structure with `content.json` and `images` folder added in a subdirectory named content of the root directory with the `h5p.json`.

**Actual content structure**
```
├── content.json
├── h5p.json
└── images
    ├── image-5d024c6012b73-O5bw5yg-q.png
    ├── image-5d024db3bd4e4-Aiptsd9hA1.JPG
```

**h5p content structure inside the zip**
```
├── h5p.json
├── content
│   ├── content.json
│   └── images
│       ├── image-5d024c6012b73.png
│       ├── image-5d024db3bd4e4.JPG
```

**Comment by sr258** [comment]
I'm aware of the difference. The reason that FileContentStorage behaves that way is that the `content` folder is redundant if you only store content and not the libraries. In the h5p packages it makes sense to have the folder, as they separate content and library code. FileContentStorage was not designed with h5p-standalone compatibility in mind. I see the use case, though. It should not be terribly difficult to change the behaviour, but we must make sure that the storage is still backwards compatible with directory structures that don't use the `content` folder. I welcome pull requests here!

**Comment by sr258** [comment]
BTW: The NodeJS player should work fine, why not simply use it?

**Comment by benabel** [comment]
I understand this redundancy you're right. This should be handled outside of the h5p-nodejs-library.

**Comment by benabel** [comment]
> BTW: The NodeJS player should work fine, why not simply use it?

Because I want to offer content statically.

**Comment by sr258** [comment]
A possible solution could be to have an optional h5p-standalone compatibility mode in the storage class. This doesn't disrupt normal operations and would help you out.

**Comment by benabel** [comment]
In fact I used the packageexporter script to create h5 files as I also want to make them accessible.

Thanks for your support, this is a really nice library.
