### ISSUE TITLE
Opinions on Domain Model?

### ISSUE THREAD

**Issue by rtens** [Lumieducation/H5P-Nodejs-library#57]
Hey @JPSchellenberg and @sr258

I thought about the domain model today and wanted to know what you guys think about it. Sebastian already started with classes for the [Library](https://github.com/sr258/H5P-Editor-Nodejs-library/blob/hub-install/src/library.js) and [Content Type](https://github.com/sr258/H5P-Editor-Nodejs-library/blob/hub-install/src/content-type.js) and I think if we pushed that further and designed a full domain model, we could reduce complexity in both the interface and the implementation.

Here my proposal. The listed properties are not exhaustive.

Looking forward to your comments.

### Library

Arguably the most important entity. A Library is everything that can be found in the library folders in an H5P file, including the properies stored in `library.json`, its semantics, hook and upgrade functions, its scripts, styles and other assets.

```
Library
- title:String
- machineName:String
- version:Version
- coreApi:{version:Version}
- styles:[Asset]
- scripts:[Asset]
- dependencies:[Library]
- editorDependencies:[Library]
- hooks:{preSave:Function,...}
- upgrades:{1:{2:Function}}

Version
- minor:Integer
- major:Integer
- patch:Integer

Asset
- path:String
- data:Buffer
- stream:ReadStream
```

### Content Type

A Content Type is what we get from H5P.org. It mostly describes a Library.

```
ContentType
- library:Library
- coreApiVersionNeeded:Version
- title:String
- summary:String
...
```

### Package

A Package is everything you find in an H5P file, which is not a Library, meaning the properties of the `h5p.json`, the content and its assets like images.

```
Package
- title:String
- language:String
- mainLibrary:Library
- dependencies:[Library]
- content:{}
- assets:[Asset]
```

## Implementation

Regarding the implementation I'm thinking of a mix between Active Record and Repository pattern. Repositories would be used to load entities, and the entities themselves to save changes and access properties. Each entity would be a proxy, loading properties and references lazily. This means that properties could only be access via async methods which might feel a bit awkward but I think it's worth the gain of clearer interaction patterns.

**Comment by sr258** [comment]
I think making the project properly object oriented would be great to simplify the development process and to produce much cleaner and readable code! It cries out for TypeScript in my opinion, though. Do the people in Bremen really require pure JavaScript? We compile down to ES5 anyway, which can be done from TypeScript, too!

Before I go into the actual domain model, my thoughts on the patterns: I fully agree with using the Repository pattern and I understand the theoretical appeal of the Active Record, but would also warn of the complexity that this introduces. We should identify the cases in which lazy loading of properties is really required. If these are only few, it would maybe be worth having a repositories with more methods that do eager loading. As there are relatively few instances where changes to existing models will have to be saved, it might also be easier to a save(...) method in the repository, too. 

About the model:

I've created JSON schemas for the PackageValidator [here](https://github.com/sr258/H5P-Editor-Nodejs-library/tree/hub-install/src/schemas). They represent what is allowed in content.json and h5p.json and their content could be added to the schema above.

We also need models for these entities:

### UserContentState 
Stores what a learner did in some piece of content.

### User
Needed to associate content types with creators, manage update / install privileges.

```
User
- name: String
- canInstallRecommended: Boolean
- canUpdateAndInstallLibraries: Boolean
- canCreateRestricted: Boolean
```

### Log & LogEntry
H5P logs activity creation (to send usage statistics to the Hub) with these.

**Comment by JPSchellenberg** [comment]
I agree with @sr258 as I would like to use Typescript too. The main reason behind the decision in favor of Javascript was to make the project more appealing to new contributors as more people know javascript than typescript. But I think we benefit more from Typescript in the long-shot as it makes the project more maintainable.

**Comment by rtens** [comment]
For me the designs decisions are mostly independent of if we use TypeScript or not. So I would like to focus on the design.

@sr258 Thanks for entities. I hadn't considered the User side of things at all.
I understand your concerns regarding implementation complexity but I think the reduced interface complexity might be worth it. Also, I think loading properties lazily would work especially well since we have no or just very few reasons to update any entities. I'll make a draft of the implementation when the time comes.7

---

Since I don't think the project is currently in a good state for a redesign I'll close this issue and would open a new one when it's at a more stable point.
