### ISSUE TITLE
"Travis CI - Branch Expected — Waiting for status to be reported" in Pull Requests

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#65]
The CI tests of my pull requests don't seem to pass through. One is always yellow and says "Travis CI - Branch Expected — Waiting for status to be reported". The fix might be found here: https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

**Comment by JPSchellenberg** [comment]
I did what the page suggested and disabled the deprecated `continuous-integration/travis-ci` check, but stills runs and receives no information. I will try to setup travis from scratch.
<img width="671" alt="Screenshot 2019-08-29 at 09 47 34" src="https://user-images.githubusercontent.com/9697985/63920890-0e6a2380-ca42-11e9-9dc1-889243db25ef.png">

**Comment by JPSchellenberg** [comment]
I reinstalled travis and tried to move everything from travis-ci.org to travis-ci.com but it still shows this error message in PR #66 so I removed the "Branch" option and now travis only runs for PRs.
