### ISSUE TITLE
Build Error on Windows: 'sh' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by GokulNC** [Lumieducation/H5P-Nodejs-library#703]
Here's a snippet from the error log during `npm install`:

```
> sh scripts/install.sh

'sh' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! h5p-nodejs-library@2.0.0 download:h5p: `sh scripts/install.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the h5p-nodejs-library@2.0.0 download:h5p script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

It'd be great if you could add support for Windows too.  
(Without having to use WSL / MinGW / Cgywin)

Last but not least, thanks a lot for this library!

**Comment by sr258** [comment]
I mostly develop the library in Windows. I recommend using Git Bash as your command line, which support sh scripts. Obviously this runs with MinGW, but I never had any issues with it.

If there are benefits in supporting Windows batch files natively, it should be possible to convert the scripts.

**Comment by GokulNC** [comment]
Cool, thank you!

You are right that it may not be necessary to have separate batch files for now.
Probably it might be a comfortable solution for Windows users if there were one, not necessarily immediately, but after a few months when the project is stabilized.

Please feel free to close the issue if that's not what you have planned. :)

**Comment by sr258** [comment]
As working with an alternative shell is a good workaround, I‘m not going to add the Windows batch file at this moment. I‘d be happy about a Pull request, though.
