### ISSUE TITLE
Review Library domain object

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#71]
While working on finishing the installation PR I've started working on a proper domain model for Library that follows the proxy pattern proposed by @rtens . This makes sense now as I have to move code from FileStorage to FileLibraryStorage and change method calls, so why not do it now before the code becomes bigger and there will be even more changes?

You can see the current state in the [install-proxy-library branch](https://github.com/sr258/H5P-Editor-Nodejs-library/tree/install-proxy-library/src).

Relevant classes where something has happened are Library, LibraryProxy, FileLibraryStorage and LibraryManager. The code is not tested or integrated at all, but it'd like some feedback before I continue down this lane further.

**Comment by rtens** [comment]
Sorry only now got around to take a look at this. The LibraryProxy is pretty much what I had in mind although I would probably design it a bit differently. I'll get started with a redesign of the Player to show you what exactly I had in mind.
