### ISSUE TITLE
File handling potentially causing trouble for CSS <url> usage 

### ISSUE THREAD

**Issue by otacke** [Lumieducation/H5P-Nodejs-library#734]
**Describe the bug**
It's up to interpretation whether this is a bug or a matter of implementation.

The original H5P editor library renames files that authors upload. The new file name will be a combination of the editor form field name and a 'unique' id. (cmp. https://github.com/h5p/h5p-editor-php-library/blob/master/h5peditor-file.class.php#L204). It seems, however, that the port to node.js keeps the filename and attaches a 'unique' id.

Keeping the original filename can cause trouble if it e.g. contains parentheses that end up in a <url> value of a CSS property. It's possible to not put URLs in quotes inside that value, cmp. https://developer.mozilla.org/en-US/docs/Web/CSS/url In that case parentheses (and some other characters) need to be escaped, but not all content types do (maybe due to lack of better knowledge, maybe simply relying on H5P's filename renaming). Without escaping, <url> values for images will not be valid and images won't display.

One content type failing is Memory Game that uses the <url> value for the (background) images of cards. Of course, this could also be fixed (and maybe should as it feels to be good practice to enclose URLs in quotes), but there may be other content types, too, and this could be fixed centrally in the node.js port by sticking to H5P's filename convention.

**Environment (please complete the following information):**
 - OS: any
 - Browser: any
 - Nodejs-Version: whatever Lumi uses

**To Reproduce**
Create Memory Game content using a (backside) image containing parentheses in its filename.

**Expected behavior**
Image shows (CSS <url> value is valid without being enclosed in quotes)

**Screenshots**
---

**Additional context**
---

**Comment by sr258** [comment]
Thank you for the report!

The easiest way to fix this is to include parenthesis in the sanitizing function for filenames. I'll do this soon. I was not aware how the PHP implementation creates filenames, but I think it's advisable to stick to its way of doing things to remain compatible.
