### ISSUE TITLE
Determining contentId

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#74]
Currently contentId is simply generated in the example implementation by adding the query parameter contentId=XXX to every request. At some point, this needs to be replaced with a solution that is closer to the PHP implementation. I've tried to find out how the PHP implementation assigns contentIds and so far I've found out this:

1. contentIds are integers and are not necessarily the same as the id of the CMS/LMS's content node. (Even though this would be possible if the ids of the CMS/LMS are integers too)
2. They seem to be generated by the CMS/LMS (plugin). In the moodle implementation it is simply the auto-generated key of the database entry of a saved piece of content.
3. When editing an existing content piece the contentId is passed to the editor in H5PIntegration.editor.nodeVersionId.
4. When uploading images in already existing content, the contentId is in the property ``contentId`` of the request's body (form data). It is 0 if the user is creating new content. In both cases the image is uploaded to a global temporary location, though. I'm not sure how the PHP implementation keeps track of the connection between new uploaded images and the unsaved content (that only exists in the client at this point). It looks like this is connected to the current session and not to the contentId received through the body. I've checked in the Moodle implementation: If I upload an image in an unsaved piece of content and "abort" editing by opening other Moodle pages, I can still access the image by calling the temporary URL (http://moodle/pluginfile.php/XXXXXXX/mod_hvp/editor/images/file-5d61958f640a9.png). I don't have access to it once I've logged out of moodle or from another browser with the same user. So uploaded temporary images seem to exist at session scope (and are deleted through a timeout).
5. When saving a new piece of content, the contentId is generated and there is a HTML redirect to the viewer (or to the course overview, depending on what the user clicked). There it is passed to the JavaScript client as described in 6.
6. When viewing a piece of content, the contentId is passed to the JavaScript viewer by the plugin 
     1. by setting an object to H5PIntegration.contents["cid-XXX"] and 
     2. by setting a HTML property in <div class="h5p-content" data-content-id="XXX">

All of this means that we need to finish #61 and introduce sessions to the server (https://github.com/Lumieducation/H5P-Nodejs-library/issues/46 needs to be moved back here) to be able to remove the contentId parameter.

**Comment by rtens** [comment]
Great analysis. I would like to avoid making the libraries session-aware though. So let's look for another solution.

**Comment by sr258** [comment]
I've checked out how ids are generated in MongoDB: They are strings and pretty long (12 bytes). I'm afraid that converting these ids to numbers won't work. At the same time the native MongoDB ids are useful as they work great in a DB cluster (contain machine and process id). So it would be great if we could use string ids after all. Maybe the change in the client isn't so big? Unfortunately I forgot the place where I received the NaN value from the client when the id is a strong. We'll have to find out where this is.

**Comment by JPSchellenberg** [comment]
I would also prefer strings and we should give the user the possibility to assign contentIds.
