### ISSUE TITLE
Revision of dependencies

### ISSUE THREAD

**Issue by jankapunkt** [Lumieducation/H5P-Nodejs-library#76]
Dependencies should be checked for the following criteria:

* is it a dev-dependency, which accidentally has been installed as dependency?
* is it a hard-required dependency (for example to run the editor)
* is it an optional dependency?
* ... what else?

Example: `fs-extra` is currently in dependencies but i only used as dev-dependency.

**Comment by rtens** [comment]
Turns out, `fs-extra` is used by the `FileLibraryStorage` as well so it has to stay in the production dependencies.
