### ISSUE TITLE
Detect missing libraries when uploading package

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#82]
A H5P package doesn't necessarily include all required packages, but might rely on them already being present in the system.

Before the libraries and the content is added to the system, we need to check if all required libraries will be present if the ones in the package are added to it. If not, the PackageManager needs to reject the request to add the package.

We also need to check if the content of a library is usable if the user doesn't have permission to install or update libraries. As the libraries can't be installed by him, the content won't be usable.

We have to decide what to do if the package of a user contains a new patch of a library, but the user doesn't have permission to update libraries. There are two options:

1. reject the package and tell the user to ask for an update by the administrator
2. accept the content without applying the patch (as patches don't change the semantics of a library, the content should be playable)

@rtens @JPSchellenberg Which option would you prefer here?

**Comment by rtens** [comment]
I do not have enough experience with use cases to be able to answer this question.

Gut feeling-wise I would tend to the restrictive version. If I don't trust a user to install a Library, then this includes patch updates since they add code.

All in all this seems to be a pretty low-percentage edge case which I would like to defer until we have a more stable foundation.

**Comment by sr258** [comment]
I agree that it's not high priority at the moment, but we should leave it open to remember it in the future.

**Comment by rtens** [comment]
As a general rule, I'm strongly against leaving issues open to remember them. Closing an issue doesn't mean deleting it. If an issue is important enough it will come up again by itself. If it doesn't then it's not worth doing it. And backlogs have a strong tendency to clutter up anyway so keeping it as small as possible should have priority.
