### ISSUE TITLE
Reporting back status with proper AJAX responses

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#83]
(This has also been discussed in #43. #80 is also related, as all currently unlocalizable error messages in the code need to be replaced if we've decided how to manage reporting errors)

The H5P client expects errors (and more detailed success messages) to be a part of the AJAX response in several cases.

Examples:

- it gets a (success) message about how many libraries were added or updates when the user uploads a package
- it gets a (success) message of how many updates were applied when updating content types from the hub
- it gets an (error) message with what exactly is wrong when the validation of an uploaded package fails

The PHP implementation uses a global function to add success and error messages to the AJAX response. I would like to avoid this pattern as it won't work nicely with unit tests. I also think that the domain classes shouldn't know about how they are called, as there are scenarios where they might not be called by an AJAX call at all, but are used to automate things (e.g. in CLI dev tools). Thus, it would be better if these messages were reported back to the top level with another mechanism. Suggestions:

- Option 1: Report messages by sending them as events through a Publish-Subscribe pattern.
- Option 2: Report messages by using a logging solution with log levels (like Winston)
- Option 3: Return success messages as strings and report error messages by throwing error objects.

The top level caller (i.e. the method in the implementation (h5p-demo) dealing with the AJAX request) then adds the success or error message to the AJAX response.

**Comment by JPSchellenberg** [comment]
Correct me if I am wrong, but I think we need to wait for every message before resolving the request and sending the response. So if we use for example Option 1, how do we know that there is no pending message? And if we use Option 3 then we catch just one error and report that error.
How do we check, that there are no pending messages/events before sending the response?

**Comment by sr258** [comment]
> Correct me if I am wrong, but I think we need to wait for every message before resolving the request and sending the response. So if we use for example Option 1, how do we know that there is no pending message? 

In this model, the domain model classes publish events/messages at an aggregator (the aggregator is passed to them on construction). The class dealing with the request subscribes to the messages on the aggregator before it calls the domain model classes. That way every message will be received at the top level and it has to be stored somewhere to collect all messages that the domain model classes emit. Once the domain model's promise has resolved, the calling class adds the messages to the AJAX response. There will be no more pending messages because the promise has resolved.

> And if we use Option 3 then we catch just one error and report that error.
How do we check, that there are no pending messages/events before sending the response?

Correct, there will be only one (critical) error message that aborts the execution of the request. If you want to have more than one message the domain model has to collect them itself and send them with the error object. I've done this in the PackageValidator: I construct the error object early on. Every step of the validation process that spots a non-critical error (meaning the validation can continue to find more possible errors; it will fail in the end anyway) simply appends it's error message to the error passed to it. The error is only thrown if there is a critical error that prevents further execution of the validator. 

This works quite well for the validator, but might not work in other cases: non-critical errors here mean that the overall validation has failed and that the error will have to thrown at some point. In other cases there might be non-critical errors that you want to report to the user, but that don't mean the code can't be executed or that there is no result that is returned for the AJAX call. In these cases throwing an error would not be a good way of reporting the message. So I would rule out option 3, if I think about it.

Option 2 looks like a good choice, in particular because it would allow us logging of other things. It's also more like a generalized solution of option 1. One downside is that logging typically uses actual text messages and not error ids and stuff like that. We've said that id would be better to do the localization of messages at a top level (see #44) as it's part of the presentation layer. So we have to think about this if we use a logger to report errors to the top layer. There is also the downside of "reserving" log levels (e.g. info and error) for reporting back to the user and that people who are not aware of this convention might send message to the user without knowing.

**Comment by sr258** [comment]
I've checked in the PHP implementation. Errors report these things:

```
{ 
  message: "", //  A human readable error message
  errorCode: "", // An machine readable error code that a client should be able to interpret
  details: "" // Better description of the error and possible which action to take
}
```
Errors also set the appropriate HTTP error status code.

This means that we have to use (or convert to) the error codes used by Joubel to make sure the client understands the code. Not sure what will happen if we use codes that don't exist in the JS client, but I assume this will work fine.

**Comment by JPSchellenberg** [comment]
In option 1 and 2 it sounds like the aggregator would have to be implemented by the user - or am I on the wrong track? I would always opt for the solution that makes it easier to implement for the end user. But if we use winston it should be possible to collect all messages and then resolve the final promise with all messages.

**Comment by sr258** [comment]
I've come up with this scheme:

# Proposal on reporting AJAX responses

- All H5PEditor methods that are supposed to be called by an AJAX endpoint return an object that implements / extends IAjaxResponse:
    ```ts
        interface IAjaxResponse {
            details: string;
            errorCode: string;
            message: string;
            ... payload
        }
    ```
- The H5PEditor methods have the responsibility to create and fill the objects implementing IAjaxResponse.
- The H5PEditor methods instantiate an EventAggregator and subscribe to it
   ```ts
      interface IEventAggregator {
          publish(event: {
                    type: enum { Success, Error, Information, ... },
                    context: enum { Global, Request },
                    message? : string,
                    details?: string,
                    errorCode?: string
                },
                sender: any) : Promise<void>;
          subscribe(subscriber: ISubscriber);
      }

      interface ISubscriber {
          eventWasRaised(event): Promise<void>;
      }
  ```
- The H5PEditor methods adds the EventAggregator to every method call. All method calls have to pass it to methods they call.
- When there is the need to report something to the user, methods in the system call ```await EventAggregator.publish(new Event(...))```.
  - They can set `EventAggregator.context` to `Request`. This means the message should be directly sent to the user.
  - They can set `EventAggregator.context` to `Global`. This means the event should be logged somewhere (e.g. for statistical purposes to collect telemetry).
- H5PEditor implements `ISubscriber`:
  - it collects events with the `Request` context by adding them to the `IAjaxResponse` object. The texts are localized first.
  - it relays events with the `Global` context to some logging and telemetry class (or ignores them for now).
- When the actual payload for a method call of H5PEditor is created, it is added to `IAjaxRespose` and the object returned.
- If it catches an H5PError, the error's message is added to the `IAjaxResponse` method.

------

It mixes a global event notification mechanism with the messaging mechanism that sends messages to the client. The reason I did this is that both need an aggregator, so we don't have to pass both aggregator as arguments to method calls. Of course, we could also have sub-classes for the different types of messages to make things cleaner.

@JPSchellenberg What do you think?

**Comment by sr258** [comment]
I've discarded the idea of using the event aggregator and have decided to keep things simple: The code throws errors and there is an aggregate error class that collects several errors. If the system has to report back a success message to the user, it has to use the return values of the methods it called.
