### ISSUE TITLE
Uploading images or other files broken for unsaved content

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#87]
Currently, uploading images doesn't work if the content you're editing is new and hasn't been saved before. The reason is this would require either having a temporary storage place for unsaved content or the concept of preliminary content in storage (see #61). We have to choose one path and implement it to make uploading images for unsaved content work again.

**Comment by JPSchellenberg** [comment]
I have a really hard time deciding which path to go as I don't know what fits best. I think I would go with the preliminary content. Which path would you prefer?

**Comment by sr258** [comment]
I think having preliminary content is easier to implement (just a flag, an expiration time and a method to call regularily) and it would be easy to transition to the temporary storage approach if we find any reason why preliminary content was a bad idea after all. So I vote for preliminary content. It could be implemented by extending the content of the .h5p file in the content folder we are having already. As far as I understand it this file is not handed out the client anyway, so we can add properties there that indicate that content is preliminary and when it is expired. The .h5p file (with just the preliminary marker and the expiration date) would have to be generated either when the user opens the editor or when he first saves a content file. If we generate it right away this would mean avoiding possible collisions of ids but we might have many preliminary content entries.

**Comment by JPSchellenberg** [comment]
After thinking about this for a while I think we should leave a lot of this problem to the implementation as there might be different scenarios in which one way is better than the other. The [file-content-storage](https://github.com/Lumieducation/H5P-Editor-Nodejs-library/blob/master/src/file-content-storage.js) is relying on the local file-system, but what if someone wants to use amazons S3 storage? I like that the FileManager is interchangeable, but how would it look like exactly?

**Comment by sr258** [comment]
The ContentStorage classes provided by the implementation would be unaware of preliminary content, as this would only be a flag and an date attribute in the metadata of a piece of content. Managing the creation, final storage and deletion of preliminary content would be entirely dealt with in the storage agnostic ContentManager. To the storage creating preliminary content would be the same as a regular piece of content. The actual storage of content when the user saves it would look like a content update. This works long as the storage class can deal with any kind of metadata (as we'd extend what's in h5p.json). 

Switching between the two modes isn't that easy as the different solutions would lead to changes in several places and make the code more complex.

**Comment by JPSchellenberg** [comment]
That sounds good, so I would opt for the preliminary content.

**Comment by sr258** [comment]
I've given this some thought and have come to the conclusion that a temporary storage is better after all. This is particularly the case because the user might modify the preliminary object in the client if it has already been saved before and abort editing. In this situation we want the original state to be unchanged.
