### ISSUE TITLE
Tests fail in Windows 10

### ISSUE THREAD

**Issue by sr258** [Lumieducation/H5P-Nodejs-library#89]
Several (all of the library validation) tests fail in a Windows environment even though they work fine on Linux (and in WSL bash on Windows). We should fix this to encourage development by developers who prefer Windows. 

The reason for the errors might be connected to how paths are formed in Windows (using backslashes).

**Comment by sr258** [comment]
Looks like one of the reasons is that paths in the validator are built with backslashes (\\) but adm-zip operates with slashes. The zip spec generally operates with slashes. This means that the validator needs to be changed from using path.join to concatenating paths on its own by using slashes.

**Comment by JPSchellenberg** [comment]
I totally agree with you - it should also run on windows. I don't have a windows machine at the moment, but I will try to get a CI working with appveyor, so we can run the tests on windows with every PR.
