### ISSUE TITLE
CI: Move to CircleCI

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumieducation/H5P-Nodejs-library#90]
Hey,

as Travis CI always gets stuck with the #65 "Waiting for status to be reported" and I am running out of ideas how to fix it and we are thinking about testing on windows too, I figured out that [CircleCI](https://circleci.com) might be a viable solution as it supports windows. 

So we have two options:
Option 1: Run everything on CircleCI
Option 2: Fix Travis and run Linux there and add Appveyor for Windows tests. But I would need help to fix #65 

@rtens @sr258 Which option do you prefer?

**Comment by sr258** [comment]
I don't mind which CI service we use, but I think CircleCI doesn't include Windows builds in its free plan. I have zero experience with CI services, so I certainly don't know more than you here. 2 of the three travis jobs worked all right. So maybe we just don't run the third job? (Don't know which one this was.)

**Comment by JPSchellenberg** [comment]
I think I got Travis running again. (The projects show up on travis-ci.org and travis-ci.com but can only be configured on travis-ci.org) 
You seem right: CircleCI has no free plan for windows, so I will set up appveyor.com
