### ISSUE TITLE
LTI endpoints

### ISSUE THREAD

**Issue by tomgross** [Lumieducation/H5P-Nodejs-library#928]
**Describe the solution you'd like**
With LTI the integration of H5P in an LMS is seamless. One is able to track points and link students. Are there any plans to implement LTI on top of the Nodejs library?

**Additional context**
h5p.com from Joubel supports LIT

**Comment by sr258** [comment]
Someone else has already added this on top of our library: https://github.com/kiron/h5p-lti-1p0-provider I haven't given it a try, so I can't vouch for it. I'm particularly not sure how generic their solution is or whether it only works in a kiron environment. 

There are no plans to integrate this into the core library.
